-- +goose Up
CREATE TABLE public.gfg_game_collection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name varchar(160) NOT NULL,
    name_en varchar(160) NOT NULL,
    info varchar(500) NOT NULL DEFAULT '',
    info_en varchar(500) NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'draft',
    version bigint NOT NULL DEFAULT 1,
    published_at timestamptz,
    archived_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT gfg_game_collection_code_check CHECK (
        length(code) BETWEEN 1 AND 64 AND code ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
    ),
    CONSTRAINT gfg_game_collection_name_check CHECK (btrim(name) <> ''),
    CONSTRAINT gfg_game_collection_name_en_check CHECK (btrim(name_en) <> ''),
    CONSTRAINT gfg_game_collection_status_check CHECK (status IN ('draft', 'published', 'archived')),
    CONSTRAINT gfg_game_collection_version_check CHECK (version > 0),
    CONSTRAINT gfg_game_collection_archive_state_check CHECK ((status = 'archived') = (archived_at IS NOT NULL)),
    CONSTRAINT gfg_game_collection_publish_state_check CHECK (status <> 'published' OR published_at IS NOT NULL)
);
CREATE INDEX gfg_game_collection_public_index ON public.gfg_game_collection (status, published_at DESC, id DESC);

CREATE TABLE public.gfg_game_collection_item (
    collection_id bigint NOT NULL REFERENCES public.gfg_game_collection(id) ON DELETE CASCADE,
    game_id bigint NOT NULL REFERENCES public.gfg_game(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (collection_id, game_id)
);
CREATE INDEX gfg_game_collection_item_game_index ON public.gfg_game_collection_item (game_id, collection_id);

CREATE TABLE public.gfg_game_collection_home_slot (
    slot smallint PRIMARY KEY,
    collection_id bigint NOT NULL UNIQUE REFERENCES public.gfg_game_collection(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT gfg_game_collection_home_slot_range_check CHECK (slot BETWEEN 1 AND 5)
);

COMMENT ON TABLE public.gfg_game_collection IS '人工策展的游戏分区；只定义发展谱系与公开生命周期，不承担标签、推荐算法或成员排序。';
COMMENT ON COLUMN public.gfg_game_collection.id IS '分区内部主键，用于成员关系和首页槽位引用；不进入公开分区 DTO。';
COMMENT ON COLUMN public.gfg_game_collection.code IS '公开路由使用的小写连字符标识，最长 64 字符；创建后由运营写入层禁止修改。';
COMMENT ON COLUMN public.gfg_game_collection.name IS '分区中文名称；公开中文读取优先使用，英文为空时也可用于回退。';
COMMENT ON COLUMN public.gfg_game_collection.name_en IS '分区英文名称；公开英文读取优先使用，中文为空时也可用于回退。';
COMMENT ON COLUMN public.gfg_game_collection.info IS '分区中文策展简介，不用于推导成员资格或时间线顺序。';
COMMENT ON COLUMN public.gfg_game_collection.info_en IS '分区英文策展简介；缺失时公开读取可回退中文简介。';
COMMENT ON COLUMN public.gfg_game_collection.status IS '运营生命周期：draft 草稿、published 公开发布、archived 归档；公开 API 只读取 published。';
COMMENT ON COLUMN public.gfg_game_collection.version IS '运营写入的乐观并发版本，从 1 开始；后续写入层以版本校验防止覆盖并发编辑。';
COMMENT ON COLUMN public.gfg_game_collection.published_at IS '最近一次成功发布的时刻，也是公开分区列表倒序依据；撤回草稿后可保留历史值。';
COMMENT ON COLUMN public.gfg_game_collection.archived_at IS '当前归档的时刻，仅 archived 状态必须有值；恢复草稿时由写入层清空。';
COMMENT ON COLUMN public.gfg_game_collection.created_at IS '人工创建该分区的时刻，与成员游戏的发行时间无关。';
COMMENT ON COLUMN public.gfg_game_collection.updated_at IS '分区运营资料最近一次修改时刻，由写入层维护。';

COMMENT ON TABLE public.gfg_game_collection_item IS '人工维护的分区与游戏成员关系；不存人工顺序、权重或成人标记，公开时间线由游戏发行事实派生。';
COMMENT ON COLUMN public.gfg_game_collection_item.collection_id IS '所属人工策展分区；分区删除时级联删除成员关系，不删除游戏。';
COMMENT ON COLUMN public.gfg_game_collection_item.game_id IS '成员游戏主档案；游戏删除时级联移除关系，成人语义始终读取关联标签 code=adult。';
COMMENT ON COLUMN public.gfg_game_collection_item.created_at IS '人工将游戏纳入分区的时刻，不作为公开时间线排序依据。';
COMMENT ON COLUMN public.gfg_game_collection_item.updated_at IS '成员关系最近一次维护时刻，由运营写入层维护，不改变发行事实。';

COMMENT ON TABLE public.gfg_game_collection_home_slot IS '首页人工策展分区的五个固定槽位；公开读取仅保留已发布且当前浏览模式有可见成员的分区。';
COMMENT ON COLUMN public.gfg_game_collection_home_slot.slot IS '首页展示槽位，范围 1 至 5 并按升序展示；全部分区入口不入库。';
COMMENT ON COLUMN public.gfg_game_collection_home_slot.collection_id IS '槽位引用的分区，同一分区只能占一个槽位；删除分区时级联移除槽位。';
COMMENT ON COLUMN public.gfg_game_collection_home_slot.created_at IS '该首页槽位记录创建的时刻，不代表分区发布时间。';
COMMENT ON COLUMN public.gfg_game_collection_home_slot.updated_at IS '该槽位的分区指派最近一次修改时刻，由运营写入层维护。';

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN
    RAISE EXCEPTION 'Game Collection rollback would destroy curated membership; restore a verified backup or recreate an isolated database instead';
END $$;
-- +goose StatementEnd
