-- Showcase is opt-in. This migration does not enroll or rewrite existing Games.
-- +goose Up
ALTER TABLE public.gfg_game ADD COLUMN showcase_eligible boolean NOT NULL DEFAULT false;

CREATE TABLE public.gfg_showcase_campaign (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_name varchar(160) NOT NULL CHECK (btrim(internal_name) <> ''),
    content_type text NOT NULL CHECK (content_type IN ('game','crowdfunding','tabletop','merchandise','other')),
    sponsored boolean NOT NULL DEFAULT false,
    linked_game_id bigint REFERENCES public.gfg_game(id) ON DELETE SET NULL,
    state text NOT NULL DEFAULT 'draft' CHECK (state IN ('draft','published','paused','archived')),
    starts_at timestamptz,
    ends_at timestamptz,
    weight integer NOT NULL DEFAULT 100 CHECK (weight BETWEEN 1 AND 10000),
    pin_position smallint CHECK (pin_position BETWEEN 1 AND 4),
    desktop_object_key text,
    mobile_object_key text,
    focal_x double precision NOT NULL DEFAULT 0.5 CHECK (focal_x BETWEEN 0 AND 1),
    focal_y double precision NOT NULL DEFAULT 0.5 CHECK (focal_y BETWEEN 0 AND 1),
    primary_action_type text CHECK (primary_action_type IN ('game','project','product','website')),
    primary_target text,
    secondary_action_type text CHECK (secondary_action_type IN ('steam','kickstarter','website','other')),
    secondary_target text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at)
);
CREATE INDEX idx_gfg_showcase_campaign_schedule ON public.gfg_showcase_campaign(state, starts_at, ends_at);
CREATE INDEX idx_gfg_showcase_campaign_game ON public.gfg_showcase_campaign(linked_game_id);

CREATE TABLE public.gfg_showcase_campaign_locale (
    campaign_id bigint NOT NULL REFERENCES public.gfg_showcase_campaign(id) ON DELETE CASCADE,
    lang text NOT NULL CHECK (lang IN ('zh','en')),
    enabled boolean NOT NULL DEFAULT false,
    title varchar(160) NOT NULL DEFAULT '',
    summary varchar(400) NOT NULL DEFAULT '',
    tags text[] NOT NULL DEFAULT '{}' CHECK (cardinality(tags) <= 3),
    editorial_note varchar(200),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (campaign_id, lang)
);

-- Diagnostic IDs intentionally have no FK: aggregate history survives deletion.
CREATE TABLE public.gfg_showcase_daily_stat (
    stat_date date NOT NULL,
    subject_key text NOT NULL,
    subject_kind text NOT NULL CHECK (subject_kind IN ('managed','automatic')),
    campaign_id bigint,
    game_id bigint,
    reason text NOT NULL CHECK (reason IN ('editorial','sponsored','upcoming','new_release','trending')),
    valid_impressions bigint NOT NULL DEFAULT 0 CHECK (valid_impressions >= 0),
    qualified_clicks bigint NOT NULL DEFAULT 0 CHECK (qualified_clicks >= 0),
    click_artwork bigint NOT NULL DEFAULT 0 CHECK (click_artwork >= 0),
    click_title bigint NOT NULL DEFAULT 0 CHECK (click_title >= 0),
    click_primary bigint NOT NULL DEFAULT 0 CHECK (click_primary >= 0),
    click_secondary bigint NOT NULL DEFAULT 0 CHECK (click_secondary >= 0),
    impression_position_1 bigint NOT NULL DEFAULT 0 CHECK (impression_position_1 >= 0),
    impression_position_2 bigint NOT NULL DEFAULT 0 CHECK (impression_position_2 >= 0),
    impression_position_3 bigint NOT NULL DEFAULT 0 CHECK (impression_position_3 >= 0),
    impression_position_4 bigint NOT NULL DEFAULT 0 CHECK (impression_position_4 >= 0),
    session_estimate bigint NOT NULL DEFAULT 0 CHECK (session_estimate >= 0),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(stat_date, subject_key),
    CHECK (qualified_clicks <= valid_impressions),
    CHECK (qualified_clicks = click_artwork + click_title + click_primary + click_secondary)
);
CREATE INDEX idx_gfg_showcase_daily_stat_campaign ON public.gfg_showcase_daily_stat(campaign_id, stat_date);

CREATE TABLE public.gfg_showcase_analytics_daily_quality (
    stat_date date PRIMARY KEY,
    invalid_token_events bigint NOT NULL DEFAULT 0 CHECK (invalid_token_events >= 0),
    invalid_origin_events bigint NOT NULL DEFAULT 0 CHECK (invalid_origin_events >= 0),
    filtered_user_agent_events bigint NOT NULL DEFAULT 0 CHECK (filtered_user_agent_events >= 0),
    duplicate_impressions bigint NOT NULL DEFAULT 0 CHECK (duplicate_impressions >= 0),
    duplicate_clicks bigint NOT NULL DEFAULT 0 CHECK (duplicate_clicks >= 0),
    session_rate_limited bigint NOT NULL DEFAULT 0 CHECK (session_rate_limited >= 0),
    ip_rate_limited bigint NOT NULL DEFAULT 0 CHECK (ip_rate_limited >= 0),
    malformed_events bigint NOT NULL DEFAULT 0 CHECK (malformed_events >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- +goose Down
-- +goose StatementBegin
DO $$ BEGIN
    RAISE EXCEPTION 'Showcase history must be preserved; restore a verified backup to roll back';
END $$;
-- +goose StatementEnd
