-- +goose Up
-- 当前业务语义的中文元数据；仅修改 COMMENT，不修改结构、数据或函数行为。
-- 后续纠错通过新迁移前滚，不提供恢复缺失或旧语义注释的 Down。

COMMENT ON TABLE public."gfg_change_checkpoints" IS '游戏变化检测器各版本的独立有序水位；与事件投影原子提交';
COMMENT ON COLUMN public."gfg_change_checkpoints"."detector_key" IS '变化检测器的稳定标识，与 detector_version 共同定位合同';
COMMENT ON COLUMN public."gfg_change_checkpoints"."detector_version" IS '变化检测语义版本；各版本独立投影和推进水位';
COMMENT ON COLUMN public."gfg_change_checkpoints"."source_start_date" IS '可重建源证据的首个 UTC 日期；NULL 表示尚无起始证据';
COMMENT ON COLUMN public."gfg_change_checkpoints"."processed_through" IS '已连续处理完成的最后一个 UTC 日期；NULL 表示尚未完成任何一天';
COMMENT ON COLUMN public."gfg_change_checkpoints"."created_at" IS '游戏变化检测器各版本的独立有序水位的记录创建时间';
COMMENT ON COLUMN public."gfg_change_checkpoints"."updated_at" IS '游戏变化检测器各版本的独立有序水位的记录最近更新时间';

COMMENT ON TABLE public."gfg_change_events" IS '游戏规范变化事件；确定性身份，来源仅为历史合同，不外键依赖当前目录';
COMMENT ON COLUMN public."gfg_change_events"."event_key" IS '规范事件的确定性文本身份；相同来源重建得到相同键';
COMMENT ON COLUMN public."gfg_change_events"."detector_key" IS '变化检测器的稳定标识，与 detector_version 共同定位合同';
COMMENT ON COLUMN public."gfg_change_events"."detector_version" IS '变化检测语义版本；各版本独立投影和推进水位';
COMMENT ON COLUMN public."gfg_change_events"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_change_events"."projection_date" IS '事件被投影到的 UTC 日期，用于按日原子替换重建';
COMMENT ON COLUMN public."gfg_change_events"."event_at" IS '明确的生效或观察时刻；只有日粒度证据时为 NULL，不能伪造精确时间';
COMMENT ON COLUMN public."gfg_change_events"."time_basis" IS '事件时间依据 effective、observed 或 day；day 不携带 event_at';
COMMENT ON COLUMN public."gfg_change_events"."event_code" IS '检测器合同定义的业务变化类型';
COMMENT ON COLUMN public."gfg_change_events"."scope_kind" IS '事件作用范围类型，用于区分实体、地区或历史目标等范围';
COMMENT ON COLUMN public."gfg_change_events"."scope_key" IS '事件在该作用范围内的稳定身份，不跨历史跟踪区间合并变化';
COMMENT ON COLUMN public."gfg_change_events"."old_value" IS '变化前的已知语义值 JSON 对象，不使用失败噪声覆盖已知值';
COMMENT ON COLUMN public."gfg_change_events"."new_value" IS '变化后的已知语义值 JSON 对象';
COMMENT ON COLUMN public."gfg_change_events"."source_event_key" IS '来源事件确定性身份，与检测器及版本联合唯一以防重复产出';
COMMENT ON COLUMN public."gfg_change_events"."source_before_key" IS '支持变化前语义的规范源证据键';
COMMENT ON COLUMN public."gfg_change_events"."source_after_key" IS '支持变化后语义的规范源证据键';
COMMENT ON COLUMN public."gfg_change_events"."source_before_at" IS '变化前证据时刻；只有日粒度或无精确时刻时为 NULL';
COMMENT ON COLUMN public."gfg_change_events"."source_after_at" IS '变化后证据时刻；只有日粒度或无精确时刻时为 NULL';
COMMENT ON COLUMN public."gfg_change_events"."source_versions" IS '该事件依赖的事实、指标或源合同版本 JSON 对象';
COMMENT ON COLUMN public."gfg_change_events"."materialized_at" IS '规范事件最近一次物化的 UTC 时刻，不是业务变化发生时刻';

COMMENT ON TABLE public."gfg_change_registry" IS '游戏变化检测器版本注册合同；仅 Goose 修改，历史版本语义不可覆盖';
COMMENT ON COLUMN public."gfg_change_registry"."detector_key" IS '变化检测器的稳定标识，与 detector_version 共同定位合同';
COMMENT ON COLUMN public."gfg_change_registry"."detector_version" IS '变化检测语义版本；各版本独立投影和推进水位';
COMMENT ON COLUMN public."gfg_change_registry"."source_kind" IS '源证据类型 metric、fact、domain_history 或 effective_period';
COMMENT ON COLUMN public."gfg_change_registry"."source_contracts" IS '检测器依赖的规范源合同列表；不得以原始采集或当前目录替代';
COMMENT ON COLUMN public."gfg_change_registry"."detection_policy" IS '定义语义变化判定的编译策略标识';
COMMENT ON COLUMN public."gfg_change_registry"."watermark_policy" IS '定义可处理历史范围和源水位依赖的编译策略标识';
COMMENT ON COLUMN public."gfg_change_registry"."event_codes" IS '该检测器版本可产出的规范事件类型列表';
COMMENT ON COLUMN public."gfg_change_registry"."processing_grain" IS '处理粒度；当前固定为 day，即 UTC 日';
COMMENT ON COLUMN public."gfg_change_registry"."status" IS '合同状态 active 或 retired；历史版本保留明确的重建语义';
COMMENT ON COLUMN public."gfg_change_registry"."description" IS '检测器版本的业务含义和证据口径说明';
COMMENT ON COLUMN public."gfg_change_registry"."created_at" IS '游戏变化检测器版本注册合同的记录创建时间';
COMMENT ON COLUMN public."gfg_change_registry"."retired_at" IS '检测器退休的 UTC 时刻；active 时为 NULL';

COMMENT ON TABLE public."gfg_collection_jobs" IS '游戏采集持久任务；计划槽与活跃去重键保证幂等，租约由 PostgreSQL 持有';
COMMENT ON COLUMN public."gfg_collection_jobs"."id" IS '游戏采集持久任务的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_collection_jobs"."schedule_id" IS '来源调度身份；非计划来源可为 NULL，调度删除后保留任务并置空';
COMMENT ON COLUMN public."gfg_collection_jobs"."schedule_version" IS '任务建立时的调度版本；无调度来源时为 NULL';
COMMENT ON COLUMN public."gfg_collection_jobs"."job_key" IS '编译期采集能力的稳定标识；用于匹配执行器与调度合同';
COMMENT ON COLUMN public."gfg_collection_jobs"."trigger" IS '触发来源 scheduled、manual、startup_catchup、entity_created、entity_changed，历史导入还可为 legacy_import';
COMMENT ON COLUMN public."gfg_collection_jobs"."scope_type" IS '执行范围：all 全量或 game 单实体';
COMMENT ON COLUMN public."gfg_collection_jobs"."scope_id" IS '单实体范围的 游戏身份；全量范围为 NULL';
COMMENT ON COLUMN public."gfg_collection_jobs"."target" IS '保留的目标槽；游戏任务合同要求始终为 NULL';
COMMENT ON COLUMN public."gfg_collection_jobs"."tasks" IS '本任务请求执行的采集能力列表，不能为空';
COMMENT ON COLUMN public."gfg_collection_jobs"."priority" IS '进入执行队列的优先级，由创建任务时的调度或请求确定';
COMMENT ON COLUMN public."gfg_collection_jobs"."concurrency_key" IS '采集并发通道标识；同一通道最多一个运行中的 Job';
COMMENT ON COLUMN public."gfg_collection_jobs"."scheduled_for" IS '计划槽的 UTC 时刻；手动触发没有计划槽，为 NULL';
COMMENT ON COLUMN public."gfg_collection_jobs"."status" IS '任务状态 queued、running、success、partial、failed、skipped、missed 或 canceled';
COMMENT ON COLUMN public."gfg_collection_jobs"."requested_by" IS '请求创建任务的操作者或系统来源标识';
COMMENT ON COLUMN public."gfg_collection_jobs"."dedupe_key" IS '活跃任务去重键；无需去重时为 NULL';
COMMENT ON COLUMN public."gfg_collection_jobs"."claimed_by" IS '持有执行租约的采集实例身份；未领取时为 NULL';
COMMENT ON COLUMN public."gfg_collection_jobs"."lease_until" IS '执行租约的 UTC 到期时刻；用于故障后回收，不是计划时间';
COMMENT ON COLUMN public."gfg_collection_jobs"."cancel_requested_at" IS '请求取消的 UTC 时刻；NULL 表示没有取消请求';
COMMENT ON COLUMN public."gfg_collection_jobs"."created_at" IS '游戏采集持久任务的记录创建时间';
COMMENT ON COLUMN public."gfg_collection_jobs"."updated_at" IS '游戏采集持久任务的记录最近更新时间';
COMMENT ON COLUMN public."gfg_collection_jobs"."completed_at" IS '任务进入终态的 UTC 时刻；尚未结束时为 NULL';

COMMENT ON TABLE public."gfg_collection_runs" IS '游戏采集任务的执行尝试账本；同一 Job 可有多个递增尝试';
COMMENT ON COLUMN public."gfg_collection_runs"."id" IS '本次执行尝试的文本身份，用于关联原始观察及任务结果';
COMMENT ON COLUMN public."gfg_collection_runs"."job_id" IS '所属持久采集任务身份，删除任务时级联删除执行记录';
COMMENT ON COLUMN public."gfg_collection_runs"."attempt_no" IS '同一 Job 内从 1 开始的尝试序号，与 job_id 联合唯一';
COMMENT ON COLUMN public."gfg_collection_runs"."collector_instance_id" IS '执行本次尝试的采集进程实例身份';
COMMENT ON COLUMN public."gfg_collection_runs"."status" IS '尝试状态 running、success、partial、failed 或 canceled';
COMMENT ON COLUMN public."gfg_collection_runs"."scheduled_for" IS '计划槽的 UTC 时刻；手动触发没有计划槽，为 NULL';
COMMENT ON COLUMN public."gfg_collection_runs"."started_at" IS '本次执行尝试实际开始的 UTC 时刻';
COMMENT ON COLUMN public."gfg_collection_runs"."ended_at" IS '本次执行尝试结束的 UTC 时刻；运行中为 NULL';
COMMENT ON COLUMN public."gfg_collection_runs"."expected_count" IS '本次执行计划处理的实体任务数';
COMMENT ON COLUMN public."gfg_collection_runs"."attempted_count" IS '已尝试的实体任务数，等于 success_count + partial_count + failure_count';
COMMENT ON COLUMN public."gfg_collection_runs"."success_count" IS '本次尝试中完整成功的实体任务数';
COMMENT ON COLUMN public."gfg_collection_runs"."partial_count" IS '本次尝试中部分成功的实体任务数';
COMMENT ON COLUMN public."gfg_collection_runs"."failure_count" IS '本次尝试中失败的实体任务数';
COMMENT ON COLUMN public."gfg_collection_runs"."skipped_count" IS '本次尝试中未执行而跳过的实体任务数';
COMMENT ON COLUMN public."gfg_collection_runs"."schedule_delay_ms" IS '相对计划槽的启动延迟，单位毫秒且不为负';
COMMENT ON COLUMN public."gfg_collection_runs"."duration_ms" IS '本次执行耗时，单位毫秒';
COMMENT ON COLUMN public."gfg_collection_runs"."error_kind" IS '采集失败的稳定分类；无分类时为空串';
COMMENT ON COLUMN public."gfg_collection_runs"."error_message" IS '采集失败的诊断摘要；无错误时为空串';

COMMENT ON TABLE public."gfg_collection_schedules" IS '游戏采集的持久调度定义；PostgreSQL 为计划及槽位的权威来源';
COMMENT ON COLUMN public."gfg_collection_schedules"."id" IS '游戏采集的持久调度定义的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_collection_schedules"."job_key" IS '编译期采集能力的稳定标识；用于匹配执行器与调度合同';
COMMENT ON COLUMN public."gfg_collection_schedules"."name" IS '供运营识别的调度名称';
COMMENT ON COLUMN public."gfg_collection_schedules"."enabled" IS '是否允许调度器为此计划物化新的 Job';
COMMENT ON COLUMN public."gfg_collection_schedules"."schedule_kind" IS '调度方式 cron 或 interval，决定相应参数组';
COMMENT ON COLUMN public."gfg_collection_schedules"."cron_expression" IS 'cron 调度表达式；interval 模式为 NULL';
COMMENT ON COLUMN public."gfg_collection_schedules"."interval_seconds" IS '固定调度间隔，单位秒且大于零；cron 模式为 NULL';
COMMENT ON COLUMN public."gfg_collection_schedules"."anchor_at" IS 'interval 计划的 UTC 相位锚点；cron 模式为 NULL';
COMMENT ON COLUMN public."gfg_collection_schedules"."timezone" IS '解释 cron 表达式所用的时区名称';
COMMENT ON COLUMN public."gfg_collection_schedules"."misfire_policy" IS '错过槽位的处理策略：skip 跳过或 catch_up_once 补一次';
COMMENT ON COLUMN public."gfg_collection_schedules"."misfire_grace_seconds" IS '允许迟到执行的宽限秒数';
COMMENT ON COLUMN public."gfg_collection_schedules"."overlap_policy" IS '同通道重叠时的策略；当前合同仅允许 skip';
COMMENT ON COLUMN public."gfg_collection_schedules"."priority" IS 'Job 排队优先级；用于执行调度而非内容展示';
COMMENT ON COLUMN public."gfg_collection_schedules"."concurrency_key" IS '采集并发通道标识；同一通道最多一个运行中的 Job';
COMMENT ON COLUMN public."gfg_collection_schedules"."version" IS '乐观并发版本；修改时必须匹配旧版本并递增';
COMMENT ON COLUMN public."gfg_collection_schedules"."effective_from" IS '该版本调度定义开始生效的 UTC 时刻';
COMMENT ON COLUMN public."gfg_collection_schedules"."last_materialized_for" IS '最后已物化的计划槽时刻；尚无槽位时为 NULL';
COMMENT ON COLUMN public."gfg_collection_schedules"."next_scheduled_for" IS '下一个计划槽的 UTC 时刻；不可计算时为 NULL';
COMMENT ON COLUMN public."gfg_collection_schedules"."created_at" IS '游戏采集的持久调度定义的记录创建时间';
COMMENT ON COLUMN public."gfg_collection_schedules"."updated_at" IS '游戏采集的持久调度定义的记录最近更新时间';

COMMENT ON TABLE public."gfg_collection_task_results" IS '游戏采集执行中每个实体与能力的结果；与 Run 共同形成质量账本';
COMMENT ON COLUMN public."gfg_collection_task_results"."id" IS '游戏采集执行中每个实体与能力的结果的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_collection_task_results"."run_id" IS '所属执行尝试的文本身份，引用 collection_runs';
COMMENT ON COLUMN public."gfg_collection_task_results"."task_type" IS '游戏采集能力 details、news 或 players';
COMMENT ON COLUMN public."gfg_collection_task_results"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_collection_task_results"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_collection_task_results"."status" IS '单项结果 success、partial、failed 或 skipped';
COMMENT ON COLUMN public."gfg_collection_task_results"."upstream_status_code" IS '上游 HTTP 响应码；未取得响应时为零';
COMMENT ON COLUMN public."gfg_collection_task_results"."traffic_bucket" IS '本次请求所用的流量分类，用于区分上游请求来源';
COMMENT ON COLUMN public."gfg_collection_task_results"."retry_count" IS '本项采集发生的重试次数，不含首次请求';
COMMENT ON COLUMN public."gfg_collection_task_results"."duration_ms" IS '本次执行耗时，单位毫秒';
COMMENT ON COLUMN public."gfg_collection_task_results"."error_kind" IS '采集失败的稳定分类；无分类时为空串';
COMMENT ON COLUMN public."gfg_collection_task_results"."error_message" IS '采集失败的诊断摘要；无错误时为空串';
COMMENT ON COLUMN public."gfg_collection_task_results"."started_at" IS '本项能力开始执行的 UTC 时刻';
COMMENT ON COLUMN public."gfg_collection_task_results"."ended_at" IS '本项能力执行结束的 UTC 时刻；未记录时为 NULL';

COMMENT ON TABLE public."gfg_collector_instances" IS '游戏采集进程的持久身份及心跳历史；不是可随意清空的在线列表';
COMMENT ON COLUMN public."gfg_collector_instances"."instance_id" IS '每次采集进程启动产生的实例身份';
COMMENT ON COLUMN public."gfg_collector_instances"."collector_id" IS '采集器逻辑身份；多次进程启动可共享此标识';
COMMENT ON COLUMN public."gfg_collector_instances"."hostname" IS '运行该采集进程的主机名';
COMMENT ON COLUMN public."gfg_collector_instances"."version" IS '采集器二进制的版本标识，不是乐观锁版本';
COMMENT ON COLUMN public."gfg_collector_instances"."commit_sha" IS '构建该采集器二进制的 Git 提交标识';
COMMENT ON COLUMN public."gfg_collector_instances"."capabilities" IS '该采集器实例可执行的编译期能力列表';
COMMENT ON COLUMN public."gfg_collector_instances"."started_at" IS '进程本次启动的 UTC 时刻';
COMMENT ON COLUMN public."gfg_collector_instances"."last_heartbeat_at" IS '最近一次成功写入心跳的 UTC 时刻';
COMMENT ON COLUMN public."gfg_collector_instances"."stopped_at" IS '正常退出记录的 UTC 时刻；异常退出或仍运行时可为 NULL';

COMMENT ON TABLE public."gfg_fact_rollup_checkpoints" IS '游戏历史事实流水线的有序水位；与投影写入在同一事务提交';
COMMENT ON COLUMN public."gfg_fact_rollup_checkpoints"."pipeline_key" IS '事实流水线的稳定标识；每条流水线独立锁定和推进';
COMMENT ON COLUMN public."gfg_fact_rollup_checkpoints"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfg_fact_rollup_checkpoints"."source_start_date" IS '可重建源证据的首个 UTC 日期；NULL 表示尚无起始证据';
COMMENT ON COLUMN public."gfg_fact_rollup_checkpoints"."processed_through" IS '已连续处理完成的最后一个 UTC 日期；NULL 表示尚未完成任何一天';
COMMENT ON COLUMN public."gfg_fact_rollup_checkpoints"."quality_cutover_at" IS '完整采集账本开始可用的 UTC 边界；此前质量分母不可推造';
COMMENT ON COLUMN public."gfg_fact_rollup_checkpoints"."created_at" IS '游戏历史事实流水线的有序水位的记录创建时间';
COMMENT ON COLUMN public."gfg_fact_rollup_checkpoints"."updated_at" IS '游戏历史事实流水线的有序水位的记录最近更新时间';

COMMENT ON TABLE public."gfg_game" IS '运营维护的当前游戏目录；Steam 采集详情、规范发行事实与标签关系分别持有';
COMMENT ON COLUMN public."gfg_game"."id" IS '运营维护的当前游戏目录的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game"."name" IS '运营维护的中文游戏名称';
COMMENT ON COLUMN public."gfg_game"."name_en" IS '运营维护的英文游戏名称';
COMMENT ON COLUMN public."gfg_game"."info" IS '运营维护的中文纯文本摘要，不是上游详细 HTML 正文';
COMMENT ON COLUMN public."gfg_game"."info_en" IS '运营维护的英文纯文本摘要，不是上游详细 HTML 正文';
COMMENT ON COLUMN public."gfg_game"."create_time" IS '运营维护的当前游戏目录的记录创建时间';
COMMENT ON COLUMN public."gfg_game"."update_time" IS '运营维护的当前游戏目录的记录最近更新时间';
COMMENT ON COLUMN public."gfg_game"."resources" IS '游戏资源入口的键值列表 JSON；未配置时为 NULL';
COMMENT ON COLUMN public."gfg_game"."groups" IS '游戏社群入口的键值列表 JSON；未配置时为 NULL';
COMMENT ON COLUMN public."gfg_game"."release_date" IS '历史人工发行日期原文，仅保留兼容和追溯；不作为当前规范发行状态';
COMMENT ON COLUMN public."gfg_game"."developers" IS '运营维护的开发者列表 JSON';
COMMENT ON COLUMN public."gfg_game"."publishers" IS '运营维护的发行商列表 JSON';
COMMENT ON COLUMN public."gfg_game"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game"."header" IS '当前游戏头图来源值，按游戏素材读取合同解析';
COMMENT ON COLUMN public."gfg_game"."links" IS '游戏外部链接列表 JSON；未配置时为 NULL';
COMMENT ON COLUMN public."gfg_game"."weight" IS '当前游戏列表排序权重；weight 排序按升序及游戏身份稳定排列，不是展柜抽样权重';
COMMENT ON COLUMN public."gfg_game"."view_count" IS '游戏页面累计访问计数，不是 Steam 在线人数';
COMMENT ON COLUMN public."gfg_game"."showcase_eligible" IS '是否允许运营自动展柜候选发现；默认 false，开启后仍须满足安全、语言、素材与候选池条件';

COMMENT ON TABLE public."gfg_game_assets" IS '游戏上游素材目录及探测结果；素材 URL 与可用性证据分开保存';
COMMENT ON COLUMN public."gfg_game_assets"."id" IS '游戏上游素材目录及探测结果的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_assets"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_assets"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_assets"."asset_type" IS '具体素材类型，如 library_capsule、library_logo、screenshot_full 或视频变体';
COMMENT ON COLUMN public."gfg_game_assets"."asset_family" IS '素材所属类别，如 library、screenshot 或 movie';
COMMENT ON COLUMN public."gfg_game_assets"."source" IS '产出该素材记录的上游接口来源标识';
COMMENT ON COLUMN public."gfg_game_assets"."lang" IS '该素材对应的上游语言代码';
COMMENT ON COLUMN public."gfg_game_assets"."media_key" IS '上游媒体在所属游戏中的稳定标识，用于去重与更新';
COMMENT ON COLUMN public."gfg_game_assets"."title" IS '上游媒体标题，未提供时为空串';
COMMENT ON COLUMN public."gfg_game_assets"."url" IS '原始上游媒体地址；不是 Managed Asset 对象键';
COMMENT ON COLUMN public."gfg_game_assets"."thumbnail_url" IS '上游提供的媒体缩略图地址';
COMMENT ON COLUMN public."gfg_game_assets"."format" IS '素材的格式标记，用于区分图像或视频编码变体';
COMMENT ON COLUMN public."gfg_game_assets"."exists" IS '最近探测是否确认素材存在；NULL 表示尚未确认，不能等同于不存在';
COMMENT ON COLUMN public."gfg_game_assets"."status_code" IS '最近素材探测的 HTTP 状态码；无响应时为零';
COMMENT ON COLUMN public."gfg_game_assets"."content_type" IS '探测响应的媒体 MIME 类型';
COMMENT ON COLUMN public."gfg_game_assets"."content_length" IS '探测响应报告的内容字节数；未取得时为零';
COMMENT ON COLUMN public."gfg_game_assets"."extra" IS '媒体类型相关的补充 JSON，如视频格式或突出展示标记';
COMMENT ON COLUMN public."gfg_game_assets"."sort_order" IS '上游媒体列表的显示顺序';
COMMENT ON COLUMN public."gfg_game_assets"."checked_at" IS '最近执行素材可用性探测的 UTC 时刻；尚未探测时为 NULL';
COMMENT ON COLUMN public."gfg_game_assets"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_assets"."updated_at" IS '游戏上游素材目录及探测结果的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_comment" IS 'GoFurry 用户游戏评论及评分；来源位置与上游 Steam 评价分别持有';
COMMENT ON COLUMN public."gfg_game_comment"."id" IS 'GoFurry 用户游戏评论及评分的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_comment"."region" IS '评论提交来源 IP 的地域解析结果，不是游戏发行地区';
COMMENT ON COLUMN public."gfg_game_comment"."content" IS '用户提交的游戏评论正文';
COMMENT ON COLUMN public."gfg_game_comment"."score" IS '用户对该游戏提交的评分，与上游评价分数无关';
COMMENT ON COLUMN public."gfg_game_comment"."create_time" IS 'GoFurry 用户游戏评论及评分的记录创建时间';
COMMENT ON COLUMN public."gfg_game_comment"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_comment"."ip" IS '提交评论的客户端地址；公开响应按隐私规则脱敏';
COMMENT ON COLUMN public."gfg_game_comment"."name" IS '评论者填写的展示名称';

COMMENT ON TABLE public."gfg_game_daily" IS '游戏每日历史维度与状态；当前日可变，closed UTC 日 finalized 后供指标读取';
COMMENT ON COLUMN public."gfg_game_daily"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfg_game_daily"."tracking_period_id" IS '游戏与 AppID 的历史跟踪区间身份，引用 gfg_game_tracking_periods';
COMMENT ON COLUMN public."gfg_game_daily"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_daily"."snapshot_at" IS '该行代表的历史快照时刻；不等同于原始证据观察时刻';
COMMENT ON COLUMN public."gfg_game_daily"."tracked_at_end" IS '在该事实日结束边界是否仍具跟踪资格';
COMMENT ON COLUMN public."gfg_game_daily"."name" IS '该历史快照的中文游戏名称，不回查当前目录改写';
COMMENT ON COLUMN public."gfg_game_daily"."name_en" IS '该历史快照的英文游戏名称，不回查当前目录改写';
COMMENT ON COLUMN public."gfg_game_daily"."view_count" IS '该历史快照记录的累计访问计数，不是当日新增访问';
COMMENT ON COLUMN public."gfg_game_daily"."game_type" IS '历史 Steam 应用类型；无详情证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."is_free" IS '历史免费支持证据；未知时为 NULL，不能当作付费';
COMMENT ON COLUMN public."gfg_game_daily"."windows" IS '历史 Windows 平台支持证据；未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."mac" IS '历史 macOS 平台支持证据；未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."linux" IS '历史 Linux 平台支持证据；未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_availability" IS '历史规范发行可用性；无规范证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_precision" IS '历史规范发行日期精度；无规范证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_exact_date" IS '历史精确发行日；非 day 精度或未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_year" IS '历史规范发行年份；无对应证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_month" IS '历史规范发行月份；无对应精度或未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_quarter" IS '历史规范发行季度；无对应精度或未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_window_start" IS '历史发行日期窗口的包含起点；未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_window_end" IS '历史发行日期窗口的包含终点；未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."release_observed_at" IS '历史规范发行状态的实际观察时刻；沿用时不刷新';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_precision" IS '历史首次可用日期精度；未建立事实时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_exact_date" IS '历史首次可用精确日；非 day 精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_year" IS '历史首次可用年份；无证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_month" IS '历史首次可用月份；无对应精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_quarter" IS '历史首次可用季度；无对应精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_window_start" IS '历史首次可用窗口的包含起点；无证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_window_end" IS '历史首次可用窗口的包含终点；无证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_source" IS '历史首次可用事实来源，区分人工、可用性转变与回填';
COMMENT ON COLUMN public."gfg_game_daily"."first_available_inferred" IS '历史首次可用事实是否为推断；未建立事实时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."language_codes" IS '历史规范语言代码集合；尚无语言证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."unknown_language_names" IS '历史上游未识别语言名称集合；尚无语言证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."full_audio_language_codes" IS '历史确认完整配音的语言代码集合；尚无语言证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."languages_observed_at" IS '历史语言事实实际观察时刻；沿用证据不刷新';
COMMENT ON COLUMN public."gfg_game_daily"."developers" IS '历史快照中的开发者名称数组';
COMMENT ON COLUMN public."gfg_game_daily"."publishers" IS '历史快照中的发行商名称数组';
COMMENT ON COLUMN public."gfg_game_daily"."primary_tag_id" IS '该历史快照的主标签身份；未分配时为 NULL，后续归档不改写';
COMMENT ON COLUMN public."gfg_game_daily"."secondary_tag_id" IS '该历史快照的次标签身份；未分配时为 NULL，后续归档不改写';
COMMENT ON COLUMN public."gfg_game_daily"."tag_ids" IS '该历史快照的标签身份集合，不由当前关系回填覆盖';
COMMENT ON COLUMN public."gfg_game_daily"."details_observed_at" IS '历史 Steam 详情实际观察时刻；无详情证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."materialization_source" IS '事实来源：bootstrap 初始快照、observed 当日观察或 carried_forward 沿用先前证据';
COMMENT ON COLUMN public."gfg_game_daily"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfg_game_daily"."finalized_at" IS '历史日完成投影的 UTC 时刻；当前日可变快照为 NULL';
COMMENT ON COLUMN public."gfg_game_daily"."created_at" IS '游戏每日历史维度与状态的记录创建时间';
COMMENT ON COLUMN public."gfg_game_daily"."updated_at" IS '游戏每日历史维度与状态的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_detail_snapshots" IS 'Steam 游戏详情原始快照；按 AppID、语言、地区保留受限历史';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."id" IS 'Steam 游戏详情原始快照的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."lang" IS '该次详情请求的语言代码';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."region" IS '该次详情请求的商店地区代码';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."source" IS '详情原始快照的上游接口来源';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."payload_hash" IS '原始详情内容的哈希，用于识别相同内容快照';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."raw_payload" IS '该次上游详情响应的原始 JSON，保留以便追溯与重新解释';
COMMENT ON COLUMN public."gfg_game_detail_snapshots"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';

COMMENT ON TABLE public."gfg_game_details" IS '当前 Steam 非本地化详情；规范发行、语言与价格另有独立合同';
COMMENT ON COLUMN public."gfg_game_details"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_details"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_details"."source" IS '本次详情的上游接口来源标识';
COMMENT ON COLUMN public."gfg_game_details"."type" IS 'Steam 应用类型，如 game 或 dlc，不是运营标签';
COMMENT ON COLUMN public."gfg_game_details"."name" IS '上游详情中的游戏名称，不覆盖运营维护名称';
COMMENT ON COLUMN public."gfg_game_details"."is_free" IS '上游当前是否标记为免费；地区价格状态由价格表持有';
COMMENT ON COLUMN public."gfg_game_details"."website" IS '上游登记的游戏官网地址';
COMMENT ON COLUMN public."gfg_game_details"."header_url" IS '上游详情中的头图 URL，不是 Managed Asset 对象键';
COMMENT ON COLUMN public."gfg_game_details"."developers" IS '上游开发者列表 JSON';
COMMENT ON COLUMN public."gfg_game_details"."publishers" IS '上游发行商列表 JSON';
COMMENT ON COLUMN public."gfg_game_details"."release_coming_soon" IS '上游原始即将发行标记；业务发行判定读取规范 release_state';
COMMENT ON COLUMN public."gfg_game_details"."release_date_text" IS '上游原始发行日期文本；不能直接当作精确日期';
COMMENT ON COLUMN public."gfg_game_details"."platforms" IS 'Steam 平台支持对象 JSON，包含 Windows、macOS、Linux 证据';
COMMENT ON COLUMN public."gfg_game_details"."supported_languages" IS '上游语言支持原文；规范语言事实由 game_languages 持有';
COMMENT ON COLUMN public."gfg_game_details"."support_info" IS '上游客服支持信息 JSON';
COMMENT ON COLUMN public."gfg_game_details"."content_descriptors" IS '上游内容描述符 JSON，不替代运营 Adult 标签治理';
COMMENT ON COLUMN public."gfg_game_details"."ratings" IS '上游地区分级资料 JSON';
COMMENT ON COLUMN public."gfg_game_details"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_details"."updated_at" IS '当前 Steam 非本地化详情的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_first_available" IS '游戏首次可购买或游玩的规范日期事实；用于 New Release，建立后不随当前发行状态覆盖';
COMMENT ON COLUMN public."gfg_game_first_available"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_first_available"."precision" IS '首次可用日期精度，仅允许 day、month、quarter 或 year';
COMMENT ON COLUMN public."gfg_game_first_available"."exact_date" IS '精确发行日；只有 day 精度才有值';
COMMENT ON COLUMN public."gfg_game_first_available"."release_year" IS '首次可用事实对应的年份，建立该事实时必须已知';
COMMENT ON COLUMN public."gfg_game_first_available"."release_month" IS '规范发行月份 1..12；不是 day 或 month 精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_first_available"."release_quarter" IS '规范发行季度 1..4；非 quarter 精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_first_available"."window_start" IS '首次可用日期窗口的包含起点；必须有值，day 精度等于 exact_date';
COMMENT ON COLUMN public."gfg_game_first_available"."window_end" IS '首次可用日期窗口的包含终点；必须有值，day 精度等于 exact_date';
COMMENT ON COLUMN public."gfg_game_first_available"."source" IS '首次可用证据来源：legacy_manual、observed_transition 或 steam_backfill';
COMMENT ON COLUMN public."gfg_game_first_available"."inferred" IS '是否由 steam_backfill 推断；人工历史或实际可用性转变不标记为推断';
COMMENT ON COLUMN public."gfg_game_first_available"."source_raw" IS '建立首次可用事实所依据的原始日期文本';
COMMENT ON COLUMN public."gfg_game_first_available"."source_observed_at" IS '建立该事实的源观察时刻；历史人工证据可为 NULL';
COMMENT ON COLUMN public."gfg_game_first_available"."normalizer_version" IS '将上游原文规范化为业务事实的规则版本';
COMMENT ON COLUMN public."gfg_game_first_available"."established_at" IS '首次建立这条事实的 UTC 时刻，不是游戏发行时间';
COMMENT ON COLUMN public."gfg_game_first_available"."updated_at" IS '游戏首次可购买或游玩的规范日期事实的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_languages" IS '由 Steam US/English 证据规范化的游戏语言支持事实；未知能力保留 NULL';
COMMENT ON COLUMN public."gfg_game_languages"."id" IS '由 Steam US/English 证据规范化的游戏语言支持事实的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_languages"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_languages"."language_code" IS '规范语言代码；无法识别上游语言时为 NULL';
COMMENT ON COLUMN public."gfg_game_languages"."steam_name" IS '上游语言名称原文，用于追溯未知或映射后的语言';
COMMENT ON COLUMN public."gfg_game_languages"."steam_api_code" IS '对应 Steam API 语言代码；无映射时为 NULL';
COMMENT ON COLUMN public."gfg_game_languages"."steam_web_code" IS '对应 Steam 网页语言代码；无映射时为 NULL';
COMMENT ON COLUMN public."gfg_game_languages"."tier" IS '语言映射层级 platform、game_only 或 unknown';
COMMENT ON COLUMN public."gfg_game_languages"."interface_supported" IS '是否支持该语言界面；证据未明确时为 NULL';
COMMENT ON COLUMN public."gfg_game_languages"."subtitles_supported" IS '是否支持该语言字幕；证据未明确时为 NULL';
COMMENT ON COLUMN public."gfg_game_languages"."full_audio_supported" IS '是否支持该语言完整配音；证据未明确时为 NULL';
COMMENT ON COLUMN public."gfg_game_languages"."sort_order" IS '该语言在上游支持列表中的顺序';
COMMENT ON COLUMN public."gfg_game_languages"."source" IS '语言支持证据的上游来源标识';
COMMENT ON COLUMN public."gfg_game_languages"."source_region" IS '采集来源的商店地区代码；用于核对规范化证据';
COMMENT ON COLUMN public."gfg_game_languages"."source_locale" IS '采集来源的语言代码；用于核对规范化证据';
COMMENT ON COLUMN public."gfg_game_languages"."normalizer_version" IS '将上游原文规范化为业务事实的规则版本';
COMMENT ON COLUMN public."gfg_game_languages"."observed_at" IS '本条业务证据实际被观察到的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_languages"."updated_at" IS '由 Steam US/English 证据规范化的游戏语言支持事实的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_localized_details" IS '按语言保存的 Steam 游戏详情正文；与运营摘要分别维护';
COMMENT ON COLUMN public."gfg_game_localized_details"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_localized_details"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_localized_details"."lang" IS '该详情正文的语言代码，与 game_id 共同确定一行';
COMMENT ON COLUMN public."gfg_game_localized_details"."name" IS '该语言的上游游戏名称';
COMMENT ON COLUMN public."gfg_game_localized_details"."short_description" IS '该语言的上游简短介绍';
COMMENT ON COLUMN public."gfg_game_localized_details"."detailed_description" IS '该语言的上游详细介绍，可包含上游 HTML';
COMMENT ON COLUMN public."gfg_game_localized_details"."about_the_game" IS '该语言的上游关于游戏正文，可包含上游 HTML';
COMMENT ON COLUMN public."gfg_game_localized_details"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_localized_details"."updated_at" IS '按语言保存的 Steam 游戏详情正文的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_media" IS '游戏截图和视频的当前媒体目录，保存上游地址与顺序';
COMMENT ON COLUMN public."gfg_game_media"."id" IS '游戏截图和视频的当前媒体目录的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_media"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_media"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_media"."media_type" IS '媒体类别 screenshot 截图或 movie 视频';
COMMENT ON COLUMN public."gfg_game_media"."media_key" IS '上游媒体在所属游戏中的稳定标识，用于去重与更新';
COMMENT ON COLUMN public."gfg_game_media"."title" IS '上游媒体标题，未提供时为空串';
COMMENT ON COLUMN public."gfg_game_media"."url" IS '原始上游媒体地址；不是 Managed Asset 对象键';
COMMENT ON COLUMN public."gfg_game_media"."thumbnail_url" IS '上游提供的媒体缩略图地址';
COMMENT ON COLUMN public."gfg_game_media"."extra" IS '媒体类型相关的补充 JSON，如视频格式或突出展示标记';
COMMENT ON COLUMN public."gfg_game_media"."sort_order" IS '上游媒体列表的显示顺序';
COMMENT ON COLUMN public."gfg_game_media"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_media"."updated_at" IS '游戏截图和视频的当前媒体目录的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_news" IS '游戏上游更新新闻与公告；保存原始正文、处理后正文及互动计数';
COMMENT ON COLUMN public."gfg_game_news"."id" IS '游戏上游更新新闻与公告的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_news"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_news"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_news"."lang" IS '采集新闻使用的语言代码';
COMMENT ON COLUMN public."gfg_game_news"."event_gid" IS 'Steam 事件全局身份';
COMMENT ON COLUMN public."gfg_game_news"."announcement_gid" IS 'Steam 公告全局身份';
COMMENT ON COLUMN public."gfg_game_news"."forum_topic_id" IS '关联 Steam 论坛主题身份';
COMMENT ON COLUMN public."gfg_game_news"."headline" IS '该新闻的上游标题';
COMMENT ON COLUMN public."gfg_game_news"."raw_body" IS '上游原始正文，保留原有标记以供追溯';
COMMENT ON COLUMN public."gfg_game_news"."html" IS '从上游正文转换得到的 HTML 表示';
COMMENT ON COLUMN public."gfg_game_news"."plain_text" IS '移除正文标记后的纯文本表示';
COMMENT ON COLUMN public."gfg_game_news"."summary" IS '为新闻列表生成的正文摘要';
COMMENT ON COLUMN public."gfg_game_news"."url" IS '该新闻的上游访问地址';
COMMENT ON COLUMN public."gfg_game_news"."tags" IS '上游新闻标签列表 JSON，不是游戏分类关系';
COMMENT ON COLUMN public."gfg_game_news"."vote_up_count" IS '采集时观察到的上游赞成票数';
COMMENT ON COLUMN public."gfg_game_news"."vote_down_count" IS '采集时观察到的上游反对票数';
COMMENT ON COLUMN public."gfg_game_news"."comment_count" IS '采集时观察到的上游评论数，不是 GoFurry 评论数';
COMMENT ON COLUMN public."gfg_game_news"."raw_event" IS '上游新闻事件原始 JSON，用于追溯内容解释';
COMMENT ON COLUMN public."gfg_game_news"."published_at" IS '上游声明的新闻发布时间；未提供时为 NULL';
COMMENT ON COLUMN public."gfg_game_news"."updated_at" IS '上游声明的新闻更新时间；未提供时为 NULL，不是本地采集时间';
COMMENT ON COLUMN public."gfg_game_news"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';

COMMENT ON TABLE public."gfg_game_player_counts" IS 'Steam 在线人数原始采样与请求结果；成功值和失败诊断不得混算';
COMMENT ON COLUMN public."gfg_game_player_counts"."id" IS 'Steam 在线人数原始采样与请求结果的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_player_counts"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_player_counts"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_player_counts"."count" IS '该次成功采样的在线人数；请求失败时不能将默认零解释为零玩家';
COMMENT ON COLUMN public."gfg_game_player_counts"."status" IS '该次在线人数采集结果；统计人数仅使用成功采样';
COMMENT ON COLUMN public."gfg_game_player_counts"."upstream_status_code" IS 'Steam 响应的 HTTP 状态码；未取得响应时为零';
COMMENT ON COLUMN public."gfg_game_player_counts"."error_kind" IS '采集失败的稳定分类；无分类时为空串';
COMMENT ON COLUMN public."gfg_game_player_counts"."error_message" IS '采集失败的诊断摘要；无错误时为空串';
COMMENT ON COLUMN public."gfg_game_player_counts"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_player_counts"."run_id" IS '关联采集执行尝试的文本身份；旧采样无账本关联时为空串';

COMMENT ON TABLE public."gfg_game_player_daily" IS '按历史跟踪区间保存的 UTC 日在线人数事实及采集质量；不将手动采集混入计划质量';
COMMENT ON COLUMN public."gfg_game_player_daily"."tracking_period_id" IS '游戏与 AppID 的历史跟踪区间身份，引用 gfg_game_tracking_periods';
COMMENT ON COLUMN public."gfg_game_player_daily"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_player_daily"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_player_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfg_game_player_daily"."min_players" IS '本时间桶成功在线人数采样的最小值；没有成功采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."max_players" IS '本时间桶成功在线人数采样的最大值；没有成功采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."avg_players" IS '本时间桶成功在线人数采样的算术均值；日值直接基于原始采样，不平均小时均值';
COMMENT ON COLUMN public."gfg_game_player_daily"."median_players" IS '本时间桶成功在线人数采样的中位数；无成功采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."expected_samples" IS '计划账本应有采样数；legacy_observed_only 时为 NULL，不推造分母';
COMMENT ON COLUMN public."gfg_game_player_daily"."attempted_samples" IS '实际尝试采样数，等于 successful_samples + partial_samples + failed_samples';
COMMENT ON COLUMN public."gfg_game_player_daily"."successful_samples" IS '完整成功且可作为人数证据的采样次数';
COMMENT ON COLUMN public."gfg_game_player_daily"."partial_samples" IS '部分成功采样次数；不作为完整成功人数证据';
COMMENT ON COLUMN public."gfg_game_player_daily"."failed_samples" IS '执行失败的采样次数；不当作零人数';
COMMENT ON COLUMN public."gfg_game_player_daily"."skipped_samples" IS '账本记录跳过的计划采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."missed_samples" IS '账本记录错过的计划采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."canceled_samples" IS '账本记录取消的计划采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."unattempted_samples" IS '计划存在但没有执行尝试的采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."failure_kind_counts" IS '按失败类别汇总的次数 JSON 对象；与成功样本数分开解释';
COMMENT ON COLUMN public."gfg_game_player_daily"."first_observed_at" IS '本时间桶关联原始采样的最早观察时刻；无采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."last_observed_at" IS '本时间桶关联原始采样的最晚观察时刻；无采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."avg_observation_lag_ms" IS '实际观察相对计划槽的平均延迟毫秒数；无可比计划时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."max_observation_lag_ms" IS '实际观察相对计划槽的最大延迟毫秒数；无可比计划时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_daily"."quality_basis" IS '质量分母依据：legacy_observed_only 只有历史观察，acquisition_ledger 才有完整计划账本';
COMMENT ON COLUMN public."gfg_game_player_daily"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfg_game_player_daily"."finalized_at" IS '该闭合时间桶投影完成的 UTC 时刻；下游可据此消费 finalized 事实';
COMMENT ON COLUMN public."gfg_game_player_daily"."created_at" IS '按历史跟踪区间保存的 UTC 日在线人数事实及采集质量的记录创建时间';
COMMENT ON COLUMN public."gfg_game_player_daily"."updated_at" IS '按历史跟踪区间保存的 UTC 日在线人数事实及采集质量的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_player_hourly" IS '按历史跟踪区间保存的 UTC 小时在线人数事实及采集质量';
COMMENT ON COLUMN public."gfg_game_player_hourly"."tracking_period_id" IS '游戏与 AppID 的历史跟踪区间身份，引用 gfg_game_tracking_periods';
COMMENT ON COLUMN public."gfg_game_player_hourly"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_player_hourly"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_player_hourly"."bucket_start" IS '该小时桶的 UTC 起点，包含此时刻且不包含下一小时起点';
COMMENT ON COLUMN public."gfg_game_player_hourly"."min_players" IS '本时间桶成功在线人数采样的最小值；没有成功采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."max_players" IS '本时间桶成功在线人数采样的最大值；没有成功采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."avg_players" IS '本时间桶成功在线人数采样的算术均值；日值直接基于原始采样，不平均小时均值';
COMMENT ON COLUMN public."gfg_game_player_hourly"."median_players" IS '本时间桶成功在线人数采样的中位数；无成功采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."expected_samples" IS '计划账本应有采样数；legacy_observed_only 时为 NULL，不推造分母';
COMMENT ON COLUMN public."gfg_game_player_hourly"."attempted_samples" IS '实际尝试采样数，等于 successful_samples + partial_samples + failed_samples';
COMMENT ON COLUMN public."gfg_game_player_hourly"."successful_samples" IS '完整成功且可作为人数证据的采样次数';
COMMENT ON COLUMN public."gfg_game_player_hourly"."partial_samples" IS '部分成功采样次数；不作为完整成功人数证据';
COMMENT ON COLUMN public."gfg_game_player_hourly"."failed_samples" IS '执行失败的采样次数；不当作零人数';
COMMENT ON COLUMN public."gfg_game_player_hourly"."skipped_samples" IS '账本记录跳过的计划采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."missed_samples" IS '账本记录错过的计划采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."canceled_samples" IS '账本记录取消的计划采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."unattempted_samples" IS '计划存在但没有执行尝试的采样数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."failure_kind_counts" IS '按失败类别汇总的次数 JSON 对象；与成功样本数分开解释';
COMMENT ON COLUMN public."gfg_game_player_hourly"."first_observed_at" IS '本时间桶关联原始采样的最早观察时刻；无采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."last_observed_at" IS '本时间桶关联原始采样的最晚观察时刻；无采样时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."avg_observation_lag_ms" IS '实际观察相对计划槽的平均延迟毫秒数；无可比计划时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."max_observation_lag_ms" IS '实际观察相对计划槽的最大延迟毫秒数；无可比计划时为 NULL';
COMMENT ON COLUMN public."gfg_game_player_hourly"."quality_basis" IS '质量分母依据：legacy_observed_only 只有历史观察，acquisition_ledger 才有完整计划账本';
COMMENT ON COLUMN public."gfg_game_player_hourly"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfg_game_player_hourly"."finalized_at" IS '该闭合时间桶投影完成的 UTC 时刻；下游可据此消费 finalized 事实';
COMMENT ON COLUMN public."gfg_game_player_hourly"."created_at" IS '按历史跟踪区间保存的 UTC 小时在线人数事实及采集质量的记录创建时间';
COMMENT ON COLUMN public."gfg_game_player_hourly"."updated_at" IS '按历史跟踪区间保存的 UTC 小时在线人数事实及采集质量的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_price_daily" IS '游戏按跟踪区间和地区保存的历史日报价；保留未知与无报价语义';
COMMENT ON COLUMN public."gfg_game_price_daily"."tracking_period_id" IS '游戏与 AppID 的历史跟踪区间身份，引用 gfg_game_tracking_periods';
COMMENT ON COLUMN public."gfg_game_price_daily"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_price_daily"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_price_daily"."region" IS '价格所属商店地区代码；不同地区分别保留';
COMMENT ON COLUMN public."gfg_game_price_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfg_game_price_daily"."price_state" IS '权威价格状态 free 免费、priced 有报价、unpriced 无报价、unknown 未知；不能只看金额推断';
COMMENT ON COLUMN public."gfg_game_price_daily"."currency" IS '有报价时的币种代码；无有效报价时为 NULL';
COMMENT ON COLUMN public."gfg_game_price_daily"."initial_amount" IS '折扣前最小货币单位金额；free、unpriced、unknown 状态为 NULL 而非零';
COMMENT ON COLUMN public."gfg_game_price_daily"."final_amount" IS '折扣后最小货币单位金额；free、unpriced、unknown 状态为 NULL 而非零';
COMMENT ON COLUMN public."gfg_game_price_daily"."discount_percent" IS '有效报价的折扣百分比；无有效报价时为 NULL';
COMMENT ON COLUMN public."gfg_game_price_daily"."observed_at" IS '此报价实际被观察的 UTC 时刻；沿用时不刷新，未知时为 NULL';
COMMENT ON COLUMN public."gfg_game_price_daily"."materialization_source" IS '事实来源：bootstrap 初始快照、observed 当日观察或 carried_forward 沿用先前证据';
COMMENT ON COLUMN public."gfg_game_price_daily"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfg_game_price_daily"."finalized_at" IS '历史日投影完成的 UTC 时刻；当日可变标记尚未完成时为 NULL';
COMMENT ON COLUMN public."gfg_game_price_daily"."created_at" IS '游戏按跟踪区间和地区保存的历史日报价的记录创建时间';
COMMENT ON COLUMN public."gfg_game_price_daily"."updated_at" IS '游戏按跟踪区间和地区保存的历史日报价的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_prices" IS '当前按地区保存的 Steam 报价；价格状态与格式化展示文本分开持有';
COMMENT ON COLUMN public."gfg_game_prices"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_prices"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_prices"."region" IS '价格所属商店地区代码；不同地区分别保留';
COMMENT ON COLUMN public."gfg_game_prices"."is_free" IS '上游免费标记；业务读取以 price_state 为权威';
COMMENT ON COLUMN public."gfg_game_prices"."currency" IS '商店报价的币种代码';
COMMENT ON COLUMN public."gfg_game_prices"."initial_amount" IS '折扣前金额，单位为该币种的最小货币单位';
COMMENT ON COLUMN public."gfg_game_prices"."final_amount" IS '折扣后金额，单位为该币种的最小货币单位';
COMMENT ON COLUMN public."gfg_game_prices"."discount_percent" IS '上游折扣百分比，不是 0..1 的比例';
COMMENT ON COLUMN public."gfg_game_prices"."initial_formatted" IS '上游格式化的折扣前价格文本，仅用于展示';
COMMENT ON COLUMN public."gfg_game_prices"."final_formatted" IS '上游格式化的折扣后价格文本，仅用于展示';
COMMENT ON COLUMN public."gfg_game_prices"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_prices"."updated_at" IS '当前按地区保存的 Steam 报价的记录最近更新时间';
COMMENT ON COLUMN public."gfg_game_prices"."price_state" IS '权威价格状态 free 免费、priced 有报价、unpriced 无报价、unknown 未知；不能只看金额推断';

COMMENT ON TABLE public."gfg_game_recommendations" IS '预计算的游戏相似推荐；分类语义变化会失效缓存，保留算法版本以解释结果';
COMMENT ON COLUMN public."gfg_game_recommendations"."source_game_id" IS '请求相似推荐时的源游戏身份';
COMMENT ON COLUMN public."gfg_game_recommendations"."target_game_id" IS '该源游戏对应的推荐目标游戏身份';
COMMENT ON COLUMN public."gfg_game_recommendations"."score" IS '算法计算的原始相似度分值，范围 0..1';
COMMENT ON COLUMN public."gfg_game_recommendations"."display_score" IS '为界面展示拉伸后的相似分值，范围 0..1；不替代原始 score';
COMMENT ON COLUMN public."gfg_game_recommendations"."rank" IS '在该源游戏推荐列表中的位置';
COMMENT ON COLUMN public."gfg_game_recommendations"."reason_json" IS '用于解释推荐的理由列表 JSON';
COMMENT ON COLUMN public."gfg_game_recommendations"."algorithm_version" IS '生成此推荐结果的算法版本';
COMMENT ON COLUMN public."gfg_game_recommendations"."computed_at" IS '本条派生结果最近一次计算完成的 UTC 时刻';

COMMENT ON TABLE public."gfg_game_release_history" IS '规范发行语义变化的追加历史；保留已删除游戏的身份，不因原文字形变化制造事件';
COMMENT ON COLUMN public."gfg_game_release_history"."id" IS '规范发行语义变化的追加历史的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_release_history"."game_id" IS '发生发行语义变化的历史游戏身份；不外键依赖当前游戏目录';
COMMENT ON COLUMN public."gfg_game_release_history"."availability" IS '规范发行可用性 upcoming、available 或 unknown；不是日期精度';
COMMENT ON COLUMN public."gfg_game_release_history"."precision" IS '发行日期精度 day、month、quarter、year、tba、none 或 unknown';
COMMENT ON COLUMN public."gfg_game_release_history"."exact_date" IS '精确发行日；只有 day 精度才有值';
COMMENT ON COLUMN public."gfg_game_release_history"."release_year" IS '规范发行年份；无可用日历证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_history"."release_month" IS '规范发行月份 1..12；不是 day 或 month 精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_history"."release_quarter" IS '规范发行季度 1..4；非 quarter 精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_history"."window_start" IS '发行日期窗口的包含起点；day 精度等于 exact_date，无日历证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_history"."window_end" IS '发行日期窗口的包含终点；day 精度等于 exact_date，无日历证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_history"."raw_text" IS '用于规范化的上游发行日期原文';
COMMENT ON COLUMN public."gfg_game_release_history"."source" IS '规范发行证据来源标识；当前 Steam 合同以 US/English Storefront 为准';
COMMENT ON COLUMN public."gfg_game_release_history"."source_region" IS '采集来源的商店地区代码；用于核对规范化证据';
COMMENT ON COLUMN public."gfg_game_release_history"."source_locale" IS '采集来源的语言代码；用于核对规范化证据';
COMMENT ON COLUMN public."gfg_game_release_history"."normalizer_version" IS '将上游原文规范化为业务事实的规则版本';
COMMENT ON COLUMN public."gfg_game_release_history"."observed_at" IS '本条业务证据实际被观察到的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_release_history"."recorded_at" IS '此发行语义变化写入历史的 UTC 时刻，与 observed_at 分开保存';

COMMENT ON TABLE public."gfg_game_release_state" IS '游戏当前规范发行状态；统一使用 Steam US/English 证据，不混用本地化日期';
COMMENT ON COLUMN public."gfg_game_release_state"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_release_state"."availability" IS '规范发行可用性 upcoming、available 或 unknown；不是日期精度';
COMMENT ON COLUMN public."gfg_game_release_state"."precision" IS '发行日期精度 day、month、quarter、year、tba、none 或 unknown';
COMMENT ON COLUMN public."gfg_game_release_state"."exact_date" IS '精确发行日；只有 day 精度才有值';
COMMENT ON COLUMN public."gfg_game_release_state"."release_year" IS '规范发行年份；无可用日历证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_state"."release_month" IS '规范发行月份 1..12；不是 day 或 month 精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_state"."release_quarter" IS '规范发行季度 1..4；非 quarter 精度时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_state"."window_start" IS '发行日期窗口的包含起点；day 精度等于 exact_date，无日历证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_state"."window_end" IS '发行日期窗口的包含终点；day 精度等于 exact_date，无日历证据时为 NULL';
COMMENT ON COLUMN public."gfg_game_release_state"."raw_text" IS '用于规范化的上游发行日期原文';
COMMENT ON COLUMN public."gfg_game_release_state"."source" IS '规范发行证据来源标识；当前 Steam 合同以 US/English Storefront 为准';
COMMENT ON COLUMN public."gfg_game_release_state"."source_region" IS '采集来源的商店地区代码；用于核对规范化证据';
COMMENT ON COLUMN public."gfg_game_release_state"."source_locale" IS '采集来源的语言代码；用于核对规范化证据';
COMMENT ON COLUMN public."gfg_game_release_state"."normalizer_version" IS '将上游原文规范化为业务事实的规则版本';
COMMENT ON COLUMN public."gfg_game_release_state"."observed_at" IS '本条业务证据实际被观察到的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_release_state"."updated_at" IS '游戏当前规范发行状态的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_requirements" IS 'Steam 游戏各操作系统配置要求的当前 JSON 文档';
COMMENT ON COLUMN public."gfg_game_requirements"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_requirements"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_requirements"."pc" IS 'Windows 最低及推荐配置的上游 JSON；不是是否支持 Windows 的布尔值';
COMMENT ON COLUMN public."gfg_game_requirements"."mac" IS 'macOS 最低及推荐配置的上游 JSON；不是是否支持 macOS 的布尔值';
COMMENT ON COLUMN public."gfg_game_requirements"."linux" IS 'Linux 最低及推荐配置的上游 JSON；不是是否支持 Linux 的布尔值';
COMMENT ON COLUMN public."gfg_game_requirements"."collected_at" IS '采集器取得并持久化本条上游观察的 UTC 时刻';
COMMENT ON COLUMN public."gfg_game_requirements"."updated_at" IS 'Steam 游戏各操作系统配置要求的当前 JSON 文档的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_tag" IS '当前游戏分类的唯一关系来源；主次标签角色也由此表持有';
COMMENT ON COLUMN public."gfg_game_tag"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_tag"."tag_id" IS '分配给游戏的标签身份，引用 gfg_tag';
COMMENT ON COLUMN public."gfg_game_tag"."role" IS '标签在该游戏中的角色 normal、primary 或 secondary';
COMMENT ON COLUMN public."gfg_game_tag"."create_time" IS '当前游戏分类的唯一关系来源的记录创建时间';
COMMENT ON COLUMN public."gfg_game_tag"."update_time" IS '当前游戏分类的唯一关系来源的记录最近更新时间';

COMMENT ON TABLE public."gfg_game_tracking_periods" IS '游戏与 Steam AppID 的历史跟踪资格区间；不外键依赖当前游戏目录';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."id" IS '游戏与 Steam AppID 的历史跟踪资格区间的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."appid" IS '采集对象的 Steam AppID；与 GoFurry 游戏身份分别保存';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."tracked_from" IS '跟踪资格生效的 UTC 时刻，区间包含此起点';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."tracked_until" IS '跟踪资格失效的 UTC 时刻，区间不包含此终点；NULL 表示仍在跟踪';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."tracking_basis" IS '区间依据：explicit 明确纳入跟踪，legacy_observed 由历史观察恢复';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."opened_reason" IS '建立该历史跟踪区间的业务原因';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."closed_reason" IS '关闭该历史跟踪区间的业务原因；未关闭时为 NULL';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."created_at" IS '游戏与 Steam AppID 的历史跟踪资格区间的记录创建时间';
COMMENT ON COLUMN public."gfg_game_tracking_periods"."updated_at" IS '游戏与 Steam AppID 的历史跟踪资格区间的记录最近更新时间';

COMMENT ON TABLE public."gfg_metric_checkpoints" IS '游戏指标各版本的独立有序水位；重建不能倒退该水位';
COMMENT ON COLUMN public."gfg_metric_checkpoints"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfg_metric_checkpoints"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfg_metric_checkpoints"."source_start_date" IS '可重建源证据的首个 UTC 日期；NULL 表示尚无起始证据';
COMMENT ON COLUMN public."gfg_metric_checkpoints"."processed_through" IS '已连续处理完成的最后一个 UTC 日期；NULL 表示尚未完成任何一天';
COMMENT ON COLUMN public."gfg_metric_checkpoints"."created_at" IS '游戏指标各版本的独立有序水位的记录创建时间';
COMMENT ON COLUMN public."gfg_metric_checkpoints"."updated_at" IS '游戏指标各版本的独立有序水位的记录最近更新时间';

COMMENT ON TABLE public."gfg_metric_daily" IS '游戏指标每日全局及单维度状态计数；比例在查询时计算，不落最终百分比';
COMMENT ON COLUMN public."gfg_metric_daily"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfg_metric_daily"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfg_metric_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfg_metric_daily"."dimension_key" IS '汇总维度名；全局汇总使用 global，其它取注册合同允许的单维度';
COMMENT ON COLUMN public."gfg_metric_daily"."dimension_value" IS '该维度的历史取值；全局汇总使用 all';
COMMENT ON COLUMN public."gfg_metric_daily"."population_count" IS '实体总体数，等于 eligible_count + not_applicable_count';
COMMENT ON COLUMN public."gfg_metric_daily"."eligible_count" IS '适用实体数，等于除 not_applicable 外六种状态的计数之和';
COMMENT ON COLUMN public."gfg_metric_daily"."not_applicable_count" IS '不适用该指标的实体数，不进入适用分母';
COMMENT ON COLUMN public."gfg_metric_daily"."positive_count" IS '有明确正向证据的实体数，与 negative_count 共同组成已知分母';
COMMENT ON COLUMN public."gfg_metric_daily"."negative_count" IS '有明确反向证据的实体数；不能由未知或失败推断';
COMMENT ON COLUMN public."gfg_metric_daily"."stale_count" IS '证据已超过该版本新鲜度门槛的实体数';
COMMENT ON COLUMN public."gfg_metric_daily"."not_probed_count" IS '历史上尚未执行所需探测的实体数';
COMMENT ON COLUMN public."gfg_metric_daily"."probe_failed_count" IS '所需探测失败且不能得到有效判定的实体数';
COMMENT ON COLUMN public."gfg_metric_daily"."unknown_count" IS '证据不足以判定正反状态的实体数';
COMMENT ON COLUMN public."gfg_metric_daily"."computed_at" IS '本条派生结果最近一次计算完成的 UTC 时刻';

COMMENT ON TABLE public."gfg_metric_entity_daily" IS '游戏实体每日可解释指标状态；仅从已 finalized 的历史事实产生';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."game_id" IS 'GoFurry 游戏身份，不是 Steam AppID';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."state" IS '七态结果 positive、negative、stale、not_probed、probe_failed、unknown、not_applicable；未知不能当作否定';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."reason_code" IS '解释该实体为何进入当前指标状态的稳定原因代码';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."source_observed_at" IS '来源证据的实际观察时刻；无可用证据时为 NULL，沿用证据不刷新此时刻';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."dimension_values" IS '该历史日的维度值 JSON 对象，不回查当前目录改写历史';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."source_projection_versions" IS '所用历史事实及其投影版本的 JSON 对象';
COMMENT ON COLUMN public."gfg_metric_entity_daily"."evaluated_at" IS '本次指标状态判定完成的 UTC 时刻';

COMMENT ON TABLE public."gfg_metric_registry" IS '游戏指标版本注册合同；仅 Goose 修改，运行时和 Admin 只读';
COMMENT ON COLUMN public."gfg_metric_registry"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfg_metric_registry"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfg_metric_registry"."metric_kind" IS '指标类型；当前仅为 state_ratio，即按实体状态计算比例';
COMMENT ON COLUMN public."gfg_metric_registry"."entity_level" IS '指标实体层级；此库固定为 game';
COMMENT ON COLUMN public."gfg_metric_registry"."time_grain" IS '指标处理粒度；当前固定为 day，即 UTC 日';
COMMENT ON COLUMN public."gfg_metric_registry"."source_facts" IS '指标依赖的历史事实合同标识列表，不允许改用当前目录或原始采集替代';
COMMENT ON COLUMN public."gfg_metric_registry"."eligibility_policy" IS '判定实体是否属于指标适用总体的编译策略标识';
COMMENT ON COLUMN public."gfg_metric_registry"."state_policy" IS '由历史证据推导七态结果的编译策略标识';
COMMENT ON COLUMN public."gfg_metric_registry"."coverage_policy" IS '定义已知证据覆盖范围及统计分母的编译策略标识';
COMMENT ON COLUMN public."gfg_metric_registry"."freshness_seconds" IS '相对历史日结束时刻的证据有效秒数；NULL 表示无此新鲜度门槛';
COMMENT ON COLUMN public."gfg_metric_registry"."allowed_dimensions" IS '允许生成的单一维度名称列表；空列表表示仅全局汇总';
COMMENT ON COLUMN public."gfg_metric_registry"."status" IS '合同状态 active 或 retired；已退休版本仍可按原语义重建';
COMMENT ON COLUMN public."gfg_metric_registry"."description" IS '该指标版本的业务口径说明';
COMMENT ON COLUMN public."gfg_metric_registry"."created_at" IS '游戏指标版本注册合同的记录创建时间';
COMMENT ON COLUMN public."gfg_metric_registry"."retired_at" IS '合同停止作为活跃版本的 UTC 时刻；active 时为 NULL';

COMMENT ON TABLE public."gfg_prize" IS 'GoFurry 抽奖活动配置及奖品密钥；不是展柜推广活动';
COMMENT ON COLUMN public."gfg_prize"."id" IS 'GoFurry 抽奖活动配置及奖品密钥的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_prize"."title" IS '抽奖活动中文标题';
COMMENT ON COLUMN public."gfg_prize"."desc" IS '抽奖活动中文说明';
COMMENT ON COLUMN public."gfg_prize"."prize" IS '奖品列表 JSON，含标题、平台和可分配密钥；属于敏感运营数据';
COMMENT ON COLUMN public."gfg_prize"."key" IS '参与该抽奖活动所需的访问密钥，不是奖品激活码';
COMMENT ON COLUMN public."gfg_prize"."start_time" IS '活动允许参与的开始时间，按 Asia/Shanghai 运营墙上时间解释';
COMMENT ON COLUMN public."gfg_prize"."end_time" IS '活动允许参与的结束时间，按 Asia/Shanghai 运营墙上时间解释';
COMMENT ON COLUMN public."gfg_prize"."create_time" IS 'GoFurry 抽奖活动配置及奖品密钥的记录创建时间';
COMMENT ON COLUMN public."gfg_prize"."status" IS '活动开放开关；false 时不允许参与，即使时间窗口符合';
COMMENT ON COLUMN public."gfg_prize"."title_en" IS '抽奖活动英文标题；空串时按抽奖展示合同回退中文';
COMMENT ON COLUMN public."gfg_prize"."desc_en" IS '抽奖活动英文说明；空串时按抽奖展示合同回退中文';

COMMENT ON TABLE public."gfg_prize_member" IS '抽奖活动参与记录及中奖分配结果，包含参与者联系方式';
COMMENT ON COLUMN public."gfg_prize_member"."id" IS '抽奖活动参与记录及中奖分配结果的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_prize_member"."prize_id" IS '参与的抽奖活动身份';
COMMENT ON COLUMN public."gfg_prize_member"."name" IS '参与者填写的展示名称';
COMMENT ON COLUMN public."gfg_prize_member"."email" IS '参与者填写的联系邮箱';
COMMENT ON COLUMN public."gfg_prize_member"."ip" IS '提交参与请求的客户端来源地址';
COMMENT ON COLUMN public."gfg_prize_member"."agent" IS '参与请求的 User-Agent，用于诊断和参与风控';
COMMENT ON COLUMN public."gfg_prize_member"."is_winner" IS '该参与记录是否被选为中奖者';
COMMENT ON COLUMN public."gfg_prize_member"."prize_key" IS '分配给中奖参与者的奖品密钥；尚未分配时为 NULL，不能公开批量展示';
COMMENT ON COLUMN public."gfg_prize_member"."create_time" IS '抽奖活动参与记录及中奖分配结果的记录创建时间';

COMMENT ON TABLE public."gfg_showcase_analytics_daily_quality" IS '展柜事件校验和抗刷的每日全局质量计数；不持久化事件、IP、会话或 User-Agent';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."stat_date" IS 'Asia/Shanghai 运营日；不是 UTC 日，也不是事件原始时刻';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."invalid_token_events" IS '因 HMAC 追踪 token 校验失败而拒绝的事件数';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."invalid_origin_events" IS '因请求 Origin 不在允许范围而拒绝的事件数';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."filtered_user_agent_events" IS '因 User-Agent 过滤规则而拒绝的事件数';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."duplicate_impressions" IS '会话去重命中的重复曝光事件数，不计入有效曝光';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."duplicate_clicks" IS '会话去重命中的重复点击事件数，不计入有效点击';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."session_rate_limited" IS '会话级速率限制命中的事件数';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."ip_rate_limited" IS '来源地址级速率限制命中的事件数；这里只存计数，不存地址或地址哈希';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."malformed_events" IS '事件结构或字段无效而被拒绝的次数';
COMMENT ON COLUMN public."gfg_showcase_analytics_daily_quality"."updated_at" IS '该日 Redis 聚合绝对值最近写入 PostgreSQL 的 UTC 时刻';

COMMENT ON TABLE public."gfg_showcase_campaign" IS '首页展柜人工活动；排期、选取权重和固定位置不等同于当前已被编排展示';
COMMENT ON COLUMN public."gfg_showcase_campaign"."id" IS '首页展柜人工活动的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_showcase_campaign"."internal_name" IS '仅供后台识别的活动名称，不作为公开标题';
COMMENT ON COLUMN public."gfg_showcase_campaign"."content_type" IS '推广内容类型 game、crowdfunding、tabletop、merchandise 或 other';
COMMENT ON COLUMN public."gfg_showcase_campaign"."sponsored" IS '是否为商业推广；必须公开披露且不得填写 Editorial Note';
COMMENT ON COLUMN public."gfg_showcase_campaign"."linked_game_id" IS '关联的 GoFurry 游戏身份；非游戏活动可为空，游戏删除后置空';
COMMENT ON COLUMN public."gfg_showcase_campaign"."state" IS '活动持久状态 draft、published、paused 或 archived；展示状态还取决于排期及资格';
COMMENT ON COLUMN public."gfg_showcase_campaign"."starts_at" IS '展示排期的 UTC 起点；未配置草稿可为 NULL，后台按 Asia/Shanghai 编辑';
COMMENT ON COLUMN public."gfg_showcase_campaign"."ends_at" IS '展示排期的 UTC 终点；未配置草稿可为 NULL，到期后不参与展示';
COMMENT ON COLUMN public."gfg_showcase_campaign"."weight" IS '确定性加权选取的权重，范围 1..10000，默认 100；不决定最终展示位置';
COMMENT ON COLUMN public."gfg_showcase_campaign"."pin_position" IS '优先固定的展示位置 1..4；NULL 表示交由编排自动分配';
COMMENT ON COLUMN public."gfg_showcase_campaign"."desktop_object_key" IS '桌面 1600×800 AVIF 的 Managed Asset 对象键；未配置为 NULL，不保存 CDN 域名';
COMMENT ON COLUMN public."gfg_showcase_campaign"."mobile_object_key" IS '移动端 1200×675 AVIF 的 Managed Asset 对象键；未配置为 NULL，不保存 CDN 域名';
COMMENT ON COLUMN public."gfg_showcase_campaign"."focal_x" IS '响应式裁切的水平主体焦点，0 左侧、0.5 居中、1 右侧';
COMMENT ON COLUMN public."gfg_showcase_campaign"."focal_y" IS '响应式裁切的垂直主体焦点，0 顶部、0.5 居中、1 底部';
COMMENT ON COLUMN public."gfg_showcase_campaign"."primary_action_type" IS '主动作固定类型 game、project、product 或 website；草稿可未配置';
COMMENT ON COLUMN public."gfg_showcase_campaign"."primary_target" IS '主动作的目标值；按动作类型校验，不允许自由按钮文案代替动作合同';
COMMENT ON COLUMN public."gfg_showcase_campaign"."secondary_action_type" IS '可选次动作类型 steam、kickstarter、website 或 other';
COMMENT ON COLUMN public."gfg_showcase_campaign"."secondary_target" IS '次动作目标值；未配置次动作时为 NULL';
COMMENT ON COLUMN public."gfg_showcase_campaign"."created_at" IS '首页展柜人工活动的记录创建时间';
COMMENT ON COLUMN public."gfg_showcase_campaign"."updated_at" IS '首页展柜人工活动的记录最近更新时间';

COMMENT ON TABLE public."gfg_showcase_campaign_locale" IS '展柜活动按 zh/en 显式维护的内容；未启用或缺失语言不跨语言回退';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."campaign_id" IS '所属展柜活动身份，活动删除时级联删除语言内容';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."lang" IS '公开内容语言 zh 或 en，与活动身份共同确定一行';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."enabled" IS '是否允许该语言参加展示；默认 false';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."title" IS '该语言公开展示的活动标题';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."summary" IS '该语言公开展示的活动摘要';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."tags" IS '该语言最多三个简短展示标签，不是游戏分类关系';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."editorial_note" IS '可选编辑推荐说明；Sponsored 活动不得填写';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."created_at" IS '展柜活动按 zh/en 显式维护的内容的记录创建时间';
COMMENT ON COLUMN public."gfg_showcase_campaign_locale"."updated_at" IS '展柜活动按 zh/en 显式维护的内容的记录最近更新时间';

COMMENT ON TABLE public."gfg_showcase_daily_stat" IS '展柜主体每日合格曝光、点击及会话估算；每五分钟以绝对值幂等覆盖，不存原始事件';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."stat_date" IS 'Asia/Shanghai 运营日；不是 UTC 日，也不是事件原始时刻';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."subject_key" IS '统计主体的稳定键，用于区分人工活动与自动候选';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."subject_kind" IS '主体类别 managed 人工活动或 automatic 自动推荐';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."campaign_id" IS '人工活动的历史身份；自动推荐可为 NULL，不外键依赖当前活动';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."game_id" IS '统计关联的历史游戏身份；无关联游戏可为 NULL';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."reason" IS '展示原因 editorial、sponsored、upcoming、new_release 或 trending';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."valid_impressions" IS '通过 token、来源、限流及会话去重的有效曝光数；合格点击可补隐式曝光';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."qualified_clicks" IS '经去重和校验的有效点击总数，不超过 valid_impressions，等于四类来源之和';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."click_artwork" IS '有效点击中来自素材区域的次数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."click_title" IS '有效点击中来自标题区域的次数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."click_primary" IS '有效点击中来自主动作的次数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."click_secondary" IS '有效点击中来自次动作的次数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."impression_position_1" IS '在第 1 个展示位置记录的有效曝光数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."impression_position_2" IS '在第 2 个展示位置记录的有效曝光数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."impression_position_3" IS '在第 3 个展示位置记录的有效曝光数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."impression_position_4" IS '在第 4 个展示位置记录的有效曝光数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."session_estimate" IS 'Redis HLL 估计的该日独立会话数；跨日求和不是整个期间去重人数';
COMMENT ON COLUMN public."gfg_showcase_daily_stat"."updated_at" IS '该日 Redis 聚合绝对值最近写入 PostgreSQL 的 UTC 时刻';

COMMENT ON TABLE public."gfg_tag" IS '游戏可分配标签身份；Adult 等业务判断使用稳定 code，不依赖显示名';
COMMENT ON COLUMN public."gfg_tag"."id" IS '游戏可分配标签身份的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_tag"."name" IS '运营维护的中文分类名称';
COMMENT ON COLUMN public."gfg_tag"."name_en" IS '运营维护的英文分类名称';
COMMENT ON COLUMN public."gfg_tag"."info" IS '运营维护的中文分类说明';
COMMENT ON COLUMN public."gfg_tag"."info_en" IS '运营维护的英文分类说明';
COMMENT ON COLUMN public."gfg_tag"."create_time" IS '游戏可分配标签身份的记录创建时间';
COMMENT ON COLUMN public."gfg_tag"."update_time" IS '游戏可分配标签身份的记录最近更新时间';
COMMENT ON COLUMN public."gfg_tag"."code" IS '稳定业务代码，小写 kebab-case；普通修改不能改写，数字身份不携带业务语义';
COMMENT ON COLUMN public."gfg_tag"."category_id" IS '所属标签类别身份；恢复标签要求类别处于可用状态';
COMMENT ON COLUMN public."gfg_tag"."archived_at" IS '归档时间；NULL 表示可用，历史引用不因归档而改写';

COMMENT ON TABLE public."gfg_tag_category" IS '游戏标签类别及其显示次序；有活跃标签时不可归档';
COMMENT ON COLUMN public."gfg_tag_category"."id" IS '游戏标签类别及其显示次序的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfg_tag_category"."code" IS '稳定业务代码，小写 kebab-case；普通修改不能改写，数字身份不携带业务语义';
COMMENT ON COLUMN public."gfg_tag_category"."name" IS '运营维护的中文分类名称';
COMMENT ON COLUMN public."gfg_tag_category"."name_en" IS '运营维护的英文分类名称';
COMMENT ON COLUMN public."gfg_tag_category"."info" IS '运营维护的中文分类说明';
COMMENT ON COLUMN public."gfg_tag_category"."info_en" IS '运营维护的英文分类说明';
COMMENT ON COLUMN public."gfg_tag_category"."sort_order" IS '类别在运营与展示列表中的排序值';
COMMENT ON COLUMN public."gfg_tag_category"."archived_at" IS '归档时间；NULL 表示可用，历史引用不因归档而改写';
COMMENT ON COLUMN public."gfg_tag_category"."create_time" IS '游戏标签类别及其显示次序的记录创建时间';
COMMENT ON COLUMN public."gfg_tag_category"."update_time" IS '游戏标签类别及其显示次序的记录最近更新时间';

COMMENT ON FUNCTION public.gfg_game_prune_detail_snapshots(p_appid bigint, p_lang text, p_region text, p_keep_count integer) IS '按 AppID、语言、地区保留最新指定条数的详情原始快照，按采集时刻及身份倒序；返回删除条数';
COMMENT ON FUNCTION public.gfg_project_change_day(target_detector_key text, target_detector_version integer, target_date date) IS '按检测器及版本重建指定 UTC 日的规范游戏变化事件；使用历史语义证据，不跨跟踪区间；返回写入条数，水位由调用事务维护';
COMMENT ON FUNCTION public.gfg_project_mac_change_day(target_date date) IS '重建指定 UTC 日的 macOS 支持变化事件；从历史指标保留正反语义记忆，不跨跟踪区间；返回写入条数';
COMMENT ON FUNCTION public.gfg_project_mac_metric_day(target_date date) IS '从已完成游戏历史事实重建指定 UTC 日的 macOS 支持指标实体与汇总；返回实体条数，不自行推进水位';
COMMENT ON FUNCTION public.gfg_project_metric_day(target_metric_key text, target_metric_version integer, target_date date) IS '按指标及版本重建指定 UTC 日的游戏免费、Windows 或 Linux 指标；仅消费 finalized 事实并保存七态计数，返回实体条数';
COMMENT ON FUNCTION public.gfg_project_player_fact_day(target_date date) IS '重建指定 UTC 日的在线人数小时及日事实，完整账本以计划任务计算质量；返回两类写入条数，不把失败当零玩家或自行推进水位';
COMMENT ON FUNCTION public.gfg_project_state_fact_day(target_date date) IS '投影指定 UTC 日的游戏状态和地区价格历史，沿用证据保留观察时刻；返回游戏及价格写入条数，水位由调用事务维护';
COMMENT ON FUNCTION public.gfg_refresh_current_game_daily(target_game_id bigint, source_kind text) IS '为指定游戏刷新当前 UTC 日的可变历史快照，保留给定物化来源且 finalized_at 为 NULL；不回写已结束历史日';
