-- +goose Up
-- 当前业务语义的中文元数据；仅修改 COMMENT，不修改结构、数据或函数行为。
-- 后续纠错通过新迁移前滚，不提供恢复缺失或旧语义注释的 Down。

COMMENT ON TABLE public."gfn_background_pattern" IS '导航页背景图案目录及明暗主题默认样式；用户自定义样式另有所有者';
COMMENT ON COLUMN public."gfn_background_pattern"."id" IS '导航页背景图案目录及明暗主题默认样式的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_background_pattern"."name" IS '运营识别该素材的中文名称';
COMMENT ON COLUMN public."gfn_background_pattern"."name_en" IS '运营识别该素材的英文名称';
COMMENT ON COLUMN public."gfn_background_pattern"."object_key" IS 'Managed Asset 图案对象键，形如 nav/patterns/哈希.svg；不保存 CDN 域名';
COMMENT ON COLUMN public."gfn_background_pattern"."light_color" IS '浅色主题的默认图案颜色，十六进制颜色值';
COMMENT ON COLUMN public."gfn_background_pattern"."dark_color" IS '深色主题的默认图案颜色，十六进制颜色值';
COMMENT ON COLUMN public."gfn_background_pattern"."light_opacity" IS '浅色主题的默认图案不透明度，范围 0..1';
COMMENT ON COLUMN public."gfn_background_pattern"."dark_opacity" IS '深色主题的默认图案不透明度，范围 0..1';
COMMENT ON COLUMN public."gfn_background_pattern"."default_size_px" IS '默认图案平铺尺寸，单位像素';
COMMENT ON COLUMN public."gfn_background_pattern"."enabled" IS '是否允许该素材参与公开展示；删除状态另行约束';
COMMENT ON COLUMN public."gfn_background_pattern"."sort_order" IS '背景图案选项的展示顺序';
COMMENT ON COLUMN public."gfn_background_pattern"."deleted" IS '是否已软删除；不代表已删除云端对象';
COMMENT ON COLUMN public."gfn_background_pattern"."deleted_at" IS '素材软删除的 UTC 时刻；未删除时为 NULL';
COMMENT ON COLUMN public."gfn_background_pattern"."create_time" IS '导航页背景图案目录及明暗主题默认样式的记录创建时间';
COMMENT ON COLUMN public."gfn_background_pattern"."update_time" IS '导航页背景图案目录及明暗主题默认样式的记录最近更新时间';

COMMENT ON TABLE public."gfn_change_checkpoints" IS '网站变化检测器各版本的独立有序水位；与事件投影原子提交';
COMMENT ON COLUMN public."gfn_change_checkpoints"."detector_key" IS '变化检测器的稳定标识，与 detector_version 共同定位合同';
COMMENT ON COLUMN public."gfn_change_checkpoints"."detector_version" IS '变化检测语义版本；各版本独立投影和推进水位';
COMMENT ON COLUMN public."gfn_change_checkpoints"."source_start_date" IS '可重建源证据的首个 UTC 日期；NULL 表示尚无起始证据';
COMMENT ON COLUMN public."gfn_change_checkpoints"."processed_through" IS '已连续处理完成的最后一个 UTC 日期；NULL 表示尚未完成任何一天';
COMMENT ON COLUMN public."gfn_change_checkpoints"."created_at" IS '网站变化检测器各版本的独立有序水位的记录创建时间';
COMMENT ON COLUMN public."gfn_change_checkpoints"."updated_at" IS '网站变化检测器各版本的独立有序水位的记录最近更新时间';

COMMENT ON TABLE public."gfn_change_events" IS '网站规范变化事件；确定性身份，来源仅为历史合同，不外键依赖当前目录';
COMMENT ON COLUMN public."gfn_change_events"."event_key" IS '规范事件的确定性文本身份；相同来源重建得到相同键';
COMMENT ON COLUMN public."gfn_change_events"."detector_key" IS '变化检测器的稳定标识，与 detector_version 共同定位合同';
COMMENT ON COLUMN public."gfn_change_events"."detector_version" IS '变化检测语义版本；各版本独立投影和推进水位';
COMMENT ON COLUMN public."gfn_change_events"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_change_events"."projection_date" IS '事件被投影到的 UTC 日期，用于按日原子替换重建';
COMMENT ON COLUMN public."gfn_change_events"."event_at" IS '明确的生效或观察时刻；只有日粒度证据时为 NULL，不能伪造精确时间';
COMMENT ON COLUMN public."gfn_change_events"."time_basis" IS '事件时间依据 effective、observed 或 day；day 不携带 event_at';
COMMENT ON COLUMN public."gfn_change_events"."event_code" IS '检测器合同定义的业务变化类型';
COMMENT ON COLUMN public."gfn_change_events"."scope_kind" IS '事件作用范围类型，用于区分实体、地区或历史目标等范围';
COMMENT ON COLUMN public."gfn_change_events"."scope_key" IS '事件在该作用范围内的稳定身份，不跨历史跟踪区间合并变化';
COMMENT ON COLUMN public."gfn_change_events"."old_value" IS '变化前的已知语义值 JSON 对象，不使用失败噪声覆盖已知值';
COMMENT ON COLUMN public."gfn_change_events"."new_value" IS '变化后的已知语义值 JSON 对象';
COMMENT ON COLUMN public."gfn_change_events"."source_event_key" IS '来源事件确定性身份，与检测器及版本联合唯一以防重复产出';
COMMENT ON COLUMN public."gfn_change_events"."source_before_key" IS '支持变化前语义的规范源证据键';
COMMENT ON COLUMN public."gfn_change_events"."source_after_key" IS '支持变化后语义的规范源证据键';
COMMENT ON COLUMN public."gfn_change_events"."source_before_at" IS '变化前证据时刻；只有日粒度或无精确时刻时为 NULL';
COMMENT ON COLUMN public."gfn_change_events"."source_after_at" IS '变化后证据时刻；只有日粒度或无精确时刻时为 NULL';
COMMENT ON COLUMN public."gfn_change_events"."source_versions" IS '该事件依赖的事实、指标或源合同版本 JSON 对象';
COMMENT ON COLUMN public."gfn_change_events"."materialized_at" IS '规范事件最近一次物化的 UTC 时刻，不是业务变化发生时刻';

COMMENT ON TABLE public."gfn_change_registry" IS '网站变化检测器版本注册合同；仅 Goose 修改，历史版本语义不可覆盖';
COMMENT ON COLUMN public."gfn_change_registry"."detector_key" IS '变化检测器的稳定标识，与 detector_version 共同定位合同';
COMMENT ON COLUMN public."gfn_change_registry"."detector_version" IS '变化检测语义版本；各版本独立投影和推进水位';
COMMENT ON COLUMN public."gfn_change_registry"."source_kind" IS '源证据类型 metric、fact、domain_history 或 effective_period';
COMMENT ON COLUMN public."gfn_change_registry"."source_contracts" IS '检测器依赖的规范源合同列表；不得以原始采集或当前目录替代';
COMMENT ON COLUMN public."gfn_change_registry"."detection_policy" IS '定义语义变化判定的编译策略标识';
COMMENT ON COLUMN public."gfn_change_registry"."watermark_policy" IS '定义可处理历史范围和源水位依赖的编译策略标识';
COMMENT ON COLUMN public."gfn_change_registry"."event_codes" IS '该检测器版本可产出的规范事件类型列表';
COMMENT ON COLUMN public."gfn_change_registry"."processing_grain" IS '处理粒度；当前固定为 day，即 UTC 日';
COMMENT ON COLUMN public."gfn_change_registry"."status" IS '合同状态 active 或 retired；历史版本保留明确的重建语义';
COMMENT ON COLUMN public."gfn_change_registry"."description" IS '检测器版本的业务含义和证据口径说明';
COMMENT ON COLUMN public."gfn_change_registry"."created_at" IS '网站变化检测器版本注册合同的记录创建时间';
COMMENT ON COLUMN public."gfn_change_registry"."retired_at" IS '检测器退休的 UTC 时刻；active 时为 NULL';

COMMENT ON TABLE public."gfn_collection_jobs" IS '网站采集持久任务；计划槽与活跃去重键保证幂等，租约由 PostgreSQL 持有';
COMMENT ON COLUMN public."gfn_collection_jobs"."id" IS '网站采集持久任务的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collection_jobs"."schedule_id" IS '来源调度身份；非计划来源可为 NULL，调度删除后保留任务并置空';
COMMENT ON COLUMN public."gfn_collection_jobs"."schedule_version" IS '任务建立时的调度版本；无调度来源时为 NULL';
COMMENT ON COLUMN public."gfn_collection_jobs"."job_key" IS '编译期采集能力的稳定标识；用于匹配执行器与调度合同';
COMMENT ON COLUMN public."gfn_collection_jobs"."trigger" IS '触发来源 scheduled、manual、startup_catchup、entity_created、entity_changed';
COMMENT ON COLUMN public."gfn_collection_jobs"."scope_type" IS '执行范围：all 全量或 site 单实体，target 指定探测目标';
COMMENT ON COLUMN public."gfn_collection_jobs"."scope_id" IS '单实体范围的 网站身份；全量范围为 NULL';
COMMENT ON COLUMN public."gfn_collection_jobs"."target" IS '指定探测目标范围的地址；非 target 范围为 NULL';
COMMENT ON COLUMN public."gfn_collection_jobs"."tasks" IS '本任务请求执行的采集能力列表，不能为空';
COMMENT ON COLUMN public."gfn_collection_jobs"."priority" IS '进入执行队列的优先级，由创建任务时的调度或请求确定';
COMMENT ON COLUMN public."gfn_collection_jobs"."concurrency_key" IS '采集并发通道标识；同一通道最多一个运行中的 Job';
COMMENT ON COLUMN public."gfn_collection_jobs"."scheduled_for" IS '计划槽的 UTC 时刻；手动触发没有计划槽，为 NULL';
COMMENT ON COLUMN public."gfn_collection_jobs"."status" IS '任务状态 queued、running、success、partial、failed、skipped、missed 或 canceled';
COMMENT ON COLUMN public."gfn_collection_jobs"."requested_by" IS '请求创建任务的操作者或系统来源标识';
COMMENT ON COLUMN public."gfn_collection_jobs"."dedupe_key" IS '活跃任务去重键；无需去重时为 NULL';
COMMENT ON COLUMN public."gfn_collection_jobs"."claimed_by" IS '持有执行租约的采集实例身份；未领取时为 NULL';
COMMENT ON COLUMN public."gfn_collection_jobs"."lease_until" IS '执行租约的 UTC 到期时刻；用于故障后回收，不是计划时间';
COMMENT ON COLUMN public."gfn_collection_jobs"."cancel_requested_at" IS '请求取消的 UTC 时刻；NULL 表示没有取消请求';
COMMENT ON COLUMN public."gfn_collection_jobs"."created_at" IS '网站采集持久任务的记录创建时间';
COMMENT ON COLUMN public."gfn_collection_jobs"."updated_at" IS '网站采集持久任务的记录最近更新时间';
COMMENT ON COLUMN public."gfn_collection_jobs"."completed_at" IS '任务进入终态的 UTC 时刻；尚未结束时为 NULL';

COMMENT ON TABLE public."gfn_collection_runs" IS '网站采集任务的执行尝试账本；同一 Job 可有多个递增尝试';
COMMENT ON COLUMN public."gfn_collection_runs"."id" IS '本次执行尝试的文本身份，用于关联原始观察及任务结果';
COMMENT ON COLUMN public."gfn_collection_runs"."job_id" IS '所属持久采集任务身份，删除任务时级联删除执行记录';
COMMENT ON COLUMN public."gfn_collection_runs"."attempt_no" IS '同一 Job 内从 1 开始的尝试序号，与 job_id 联合唯一';
COMMENT ON COLUMN public."gfn_collection_runs"."collector_instance_id" IS '执行本次尝试的采集进程实例身份';
COMMENT ON COLUMN public."gfn_collection_runs"."status" IS '尝试状态 running、success、partial、failed 或 canceled';
COMMENT ON COLUMN public."gfn_collection_runs"."scheduled_for" IS '计划槽的 UTC 时刻；手动触发没有计划槽，为 NULL';
COMMENT ON COLUMN public."gfn_collection_runs"."started_at" IS '本次执行尝试实际开始的 UTC 时刻';
COMMENT ON COLUMN public."gfn_collection_runs"."ended_at" IS '本次执行尝试结束的 UTC 时刻；运行中为 NULL';
COMMENT ON COLUMN public."gfn_collection_runs"."expected_count" IS '本次执行计划处理的实体任务数';
COMMENT ON COLUMN public."gfn_collection_runs"."attempted_count" IS '已尝试的实体任务数，等于 success_count + partial_count + failure_count';
COMMENT ON COLUMN public."gfn_collection_runs"."success_count" IS '本次尝试中完整成功的实体任务数';
COMMENT ON COLUMN public."gfn_collection_runs"."partial_count" IS '本次尝试中部分成功的实体任务数';
COMMENT ON COLUMN public."gfn_collection_runs"."failure_count" IS '本次尝试中失败的实体任务数';
COMMENT ON COLUMN public."gfn_collection_runs"."skipped_count" IS '本次尝试中未执行而跳过的实体任务数';
COMMENT ON COLUMN public."gfn_collection_runs"."schedule_delay_ms" IS '相对计划槽的启动延迟，单位毫秒且不为负';
COMMENT ON COLUMN public."gfn_collection_runs"."duration_ms" IS '本次执行耗时，单位毫秒';
COMMENT ON COLUMN public."gfn_collection_runs"."error_kind" IS '采集失败的稳定分类；无分类时为空串';
COMMENT ON COLUMN public."gfn_collection_runs"."error_message" IS '采集失败的诊断摘要；无错误时为空串';

COMMENT ON TABLE public."gfn_collection_schedules" IS '网站采集的持久调度定义；PostgreSQL 为计划及槽位的权威来源';
COMMENT ON COLUMN public."gfn_collection_schedules"."id" IS '网站采集的持久调度定义的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collection_schedules"."job_key" IS '编译期采集能力的稳定标识；用于匹配执行器与调度合同';
COMMENT ON COLUMN public."gfn_collection_schedules"."name" IS '供运营识别的调度名称';
COMMENT ON COLUMN public."gfn_collection_schedules"."enabled" IS '是否允许调度器为此计划物化新的 Job';
COMMENT ON COLUMN public."gfn_collection_schedules"."schedule_kind" IS '调度方式 cron 或 interval，决定相应参数组';
COMMENT ON COLUMN public."gfn_collection_schedules"."cron_expression" IS 'cron 调度表达式；interval 模式为 NULL';
COMMENT ON COLUMN public."gfn_collection_schedules"."interval_seconds" IS '固定调度间隔，单位秒且大于零；cron 模式为 NULL';
COMMENT ON COLUMN public."gfn_collection_schedules"."anchor_at" IS 'interval 计划的 UTC 相位锚点；cron 模式为 NULL';
COMMENT ON COLUMN public."gfn_collection_schedules"."timezone" IS '解释 cron 表达式所用的时区名称';
COMMENT ON COLUMN public."gfn_collection_schedules"."misfire_policy" IS '错过槽位的处理策略：skip 跳过或 catch_up_once 补一次';
COMMENT ON COLUMN public."gfn_collection_schedules"."misfire_grace_seconds" IS '允许迟到执行的宽限秒数';
COMMENT ON COLUMN public."gfn_collection_schedules"."overlap_policy" IS '同通道重叠时的策略；当前合同仅允许 skip';
COMMENT ON COLUMN public."gfn_collection_schedules"."priority" IS 'Job 排队优先级；用于执行调度而非内容展示';
COMMENT ON COLUMN public."gfn_collection_schedules"."concurrency_key" IS '采集并发通道标识；同一通道最多一个运行中的 Job';
COMMENT ON COLUMN public."gfn_collection_schedules"."version" IS '乐观并发版本；修改时必须匹配旧版本并递增';
COMMENT ON COLUMN public."gfn_collection_schedules"."effective_from" IS '该版本调度定义开始生效的 UTC 时刻';
COMMENT ON COLUMN public."gfn_collection_schedules"."last_materialized_for" IS '最后已物化的计划槽时刻；尚无槽位时为 NULL';
COMMENT ON COLUMN public."gfn_collection_schedules"."next_scheduled_for" IS '下一个计划槽的 UTC 时刻；不可计算时为 NULL';
COMMENT ON COLUMN public."gfn_collection_schedules"."created_at" IS '网站采集的持久调度定义的记录创建时间';
COMMENT ON COLUMN public."gfn_collection_schedules"."updated_at" IS '网站采集的持久调度定义的记录最近更新时间';

COMMENT ON TABLE public."gfn_collection_task_results" IS '网站采集执行中每个实体与能力的结果；与 Run 共同形成质量账本';
COMMENT ON COLUMN public."gfn_collection_task_results"."id" IS '网站采集执行中每个实体与能力的结果的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collection_task_results"."run_id" IS '所属执行尝试的文本身份，引用 collection_runs';
COMMENT ON COLUMN public."gfn_collection_task_results"."protocol" IS '本项执行的探测协议，与 Nav 采集能力合同一致';
COMMENT ON COLUMN public."gfn_collection_task_results"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_collection_task_results"."target" IS '本项执行的探测地址，与网站身份分别保存';
COMMENT ON COLUMN public."gfn_collection_task_results"."status" IS '单项结果 success、partial、failed 或 skipped';
COMMENT ON COLUMN public."gfn_collection_task_results"."observation_id" IS '产生的原始观察身份；未产生或原始观察已裁剪时为 NULL';
COMMENT ON COLUMN public."gfn_collection_task_results"."duration_ms" IS '本次执行耗时，单位毫秒';
COMMENT ON COLUMN public."gfn_collection_task_results"."error_kind" IS '采集失败的稳定分类；无分类时为空串';
COMMENT ON COLUMN public."gfn_collection_task_results"."error_message" IS '采集失败的诊断摘要；无错误时为空串';
COMMENT ON COLUMN public."gfn_collection_task_results"."started_at" IS '本项能力开始执行的 UTC 时刻';
COMMENT ON COLUMN public."gfn_collection_task_results"."ended_at" IS '本项能力执行结束的 UTC 时刻；未记录时为 NULL';

COMMENT ON TABLE public."gfn_collector_domain" IS '网站当前探测目标配置；历史跟踪区间由独立事实合同保留';
COMMENT ON COLUMN public."gfn_collector_domain"."id" IS '网站当前探测目标配置的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collector_domain"."name" IS '探测目标的主机名主体';
COMMENT ON COLUMN public."gfn_collector_domain"."proxy" IS '是否经配置代理探测的字符串开关：1 启用，0 关闭';
COMMENT ON COLUMN public."gfn_collector_domain"."prefix" IS '附加在主机名前的前缀；未配置时为 NULL';
COMMENT ON COLUMN public."gfn_collector_domain"."tls" IS 'HTTP 探测是否使用 TLS 的字符串开关：1 为 HTTPS，0 为 HTTP';
COMMENT ON COLUMN public."gfn_collector_domain"."site_id" IS '所属网站身份；旧目标可未关联网站而为 NULL';
COMMENT ON COLUMN public."gfn_collector_domain"."deleted" IS '目标软删除标记；已删除目标不再参加正常采集';

COMMENT ON TABLE public."gfn_collector_instances" IS '网站采集进程的持久身份及心跳历史；不是可随意清空的在线列表';
COMMENT ON COLUMN public."gfn_collector_instances"."instance_id" IS '每次采集进程启动产生的实例身份';
COMMENT ON COLUMN public."gfn_collector_instances"."collector_id" IS '采集器逻辑身份；多次进程启动可共享此标识';
COMMENT ON COLUMN public."gfn_collector_instances"."hostname" IS '运行该采集进程的主机名';
COMMENT ON COLUMN public."gfn_collector_instances"."version" IS '采集器二进制的版本标识，不是乐观锁版本';
COMMENT ON COLUMN public."gfn_collector_instances"."commit_sha" IS '构建该采集器二进制的 Git 提交标识';
COMMENT ON COLUMN public."gfn_collector_instances"."capabilities" IS '该采集器实例可执行的编译期能力列表';
COMMENT ON COLUMN public."gfn_collector_instances"."started_at" IS '进程本次启动的 UTC 时刻';
COMMENT ON COLUMN public."gfn_collector_instances"."last_heartbeat_at" IS '最近一次成功写入心跳的 UTC 时刻';
COMMENT ON COLUMN public."gfn_collector_instances"."stopped_at" IS '正常退出记录的 UTC 时刻；异常退出或仍运行时可为 NULL';

COMMENT ON TABLE public."gfn_collector_log_dns" IS '仍供 Nav V1 兼容读取的 DNS 采集日志，不是规范历史事实';
COMMENT ON COLUMN public."gfn_collector_log_dns"."id" IS '仍供 Nav V1 兼容读取的 DNS 采集日志的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collector_log_dns"."name" IS '本条 DNS 探测的目标名称';
COMMENT ON COLUMN public."gfn_collector_log_dns"."a" IS 'DNS A 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."aaaa" IS 'DNS AAAA 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."mx" IS 'DNS MX 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."ns" IS 'DNS NS 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."soa" IS 'DNS SOA 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."txt" IS 'DNS TXT 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."caa" IS 'DNS CAA 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."cname" IS 'DNS CNAME 查询得到的记录 JSON；未记录该类结果时为 NULL';
COMMENT ON COLUMN public."gfn_collector_log_dns"."status" IS '采集请求结果 success 或 failure';
COMMENT ON COLUMN public."gfn_collector_log_dns"."create_time" IS '仍供 Nav V1 兼容读取的 DNS 采集日志的记录创建时间';

COMMENT ON TABLE public."gfn_collector_log_http" IS '仍供 Nav V1 兼容读取的 HTTP 采集日志，不是规范历史事实';
COMMENT ON COLUMN public."gfn_collector_log_http"."id" IS '仍供 Nav V1 兼容读取的 HTTP 采集日志的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collector_log_http"."name" IS '本条 HTTP 探测的目标名称';
COMMENT ON COLUMN public."gfn_collector_log_http"."info" IS 'HTTP 请求探测详情 JSON，保留 Nav V1 读取合同';
COMMENT ON COLUMN public."gfn_collector_log_http"."status" IS '采集请求结果 success 或 failure';
COMMENT ON COLUMN public."gfn_collector_log_http"."create_time" IS '仍供 Nav V1 兼容读取的 HTTP 采集日志的记录创建时间';

COMMENT ON TABLE public."gfn_collector_log_ping" IS '仍供 Nav V1 兼容读取的 Ping 采集日志，不是规范历史事实';
COMMENT ON COLUMN public."gfn_collector_log_ping"."id" IS '仍供 Nav V1 兼容读取的 Ping 采集日志的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collector_log_ping"."name" IS '本条 Ping 探测的目标名称';
COMMENT ON COLUMN public."gfn_collector_log_ping"."delay" IS '平均往返延迟的兼容文本，带 ms 后缀';
COMMENT ON COLUMN public."gfn_collector_log_ping"."loss" IS '丢包百分比的兼容文本，100 表示全部丢包';
COMMENT ON COLUMN public."gfn_collector_log_ping"."status" IS '探测可达性 up 或 down';
COMMENT ON COLUMN public."gfn_collector_log_ping"."create_time" IS '仍供 Nav V1 兼容读取的 Ping 采集日志的记录创建时间';

COMMENT ON TABLE public."gfn_collector_observation" IS 'Nav 原始探测观察及采集账本关联；受事实水位保护的裁剪不删除历史事实';
COMMENT ON COLUMN public."gfn_collector_observation"."id" IS 'Nav 原始探测观察及采集账本关联的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_collector_observation"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_collector_observation"."target" IS '该次观察的完整探测目标地址，与网站身份分别保存';
COMMENT ON COLUMN public."gfn_collector_observation"."protocol" IS '该次观察的探测协议，如 http、dns、ping 或 security_txt';
COMMENT ON COLUMN public."gfn_collector_observation"."status" IS '该次协议探测的结果状态；不等同于能力支持或不支持';
COMMENT ON COLUMN public."gfn_collector_observation"."observed_at" IS '本条业务证据实际被观察到的 UTC 时刻';
COMMENT ON COLUMN public."gfn_collector_observation"."duration_ms" IS '该次探测耗时毫秒数；未知时为 NULL';
COMMENT ON COLUMN public."gfn_collector_observation"."error_code" IS '探测失败的稳定诊断代码；无错误时可为 NULL';
COMMENT ON COLUMN public."gfn_collector_observation"."error_message" IS '探测失败的诊断摘要；无错误时可为 NULL';
COMMENT ON COLUMN public."gfn_collector_observation"."payload" IS '协议专属原始观察 JSON，按 schema_version 解释；不是跨协议统一状态';
COMMENT ON COLUMN public."gfn_collector_observation"."schema_version" IS '原始观察 payload 的结构版本';
COMMENT ON COLUMN public."gfn_collector_observation"."create_time" IS 'Nav 原始探测观察及采集账本关联的记录创建时间';
COMMENT ON COLUMN public."gfn_collector_observation"."job_id" IS '所属持久采集 Job；历史无账本关联时为 NULL';
COMMENT ON COLUMN public."gfn_collector_observation"."run_id" IS '所属执行尝试身份；历史无账本关联时为 NULL';
COMMENT ON COLUMN public."gfn_collector_observation"."collector_instance_id" IS '产生观察的采集进程实例；历史无关联时为 NULL';

COMMENT ON TABLE public."gfn_fact_rollup_checkpoints" IS '网站历史事实流水线的有序水位；与投影写入在同一事务提交';
COMMENT ON COLUMN public."gfn_fact_rollup_checkpoints"."pipeline_key" IS '事实流水线的稳定标识；每条流水线独立锁定和推进';
COMMENT ON COLUMN public."gfn_fact_rollup_checkpoints"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfn_fact_rollup_checkpoints"."source_start_date" IS '可重建源证据的首个 UTC 日期；NULL 表示尚无起始证据';
COMMENT ON COLUMN public."gfn_fact_rollup_checkpoints"."processed_through" IS '已连续处理完成的最后一个 UTC 日期；NULL 表示尚未完成任何一天';
COMMENT ON COLUMN public."gfn_fact_rollup_checkpoints"."quality_cutover_at" IS '完整采集账本开始可用的 UTC 边界；此前质量分母不可推造';
COMMENT ON COLUMN public."gfn_fact_rollup_checkpoints"."created_at" IS '网站历史事实流水线的有序水位的记录创建时间';
COMMENT ON COLUMN public."gfn_fact_rollup_checkpoints"."updated_at" IS '网站历史事实流水线的有序水位的记录最近更新时间';

COMMENT ON TABLE public."gfn_featured_site" IS '导航精选网站与运营选取权重';
COMMENT ON COLUMN public."gfn_featured_site"."id" IS '导航精选网站与运营选取权重的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_featured_site"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_featured_site"."weight" IS '精选网站展示权重，按降序排列，同值按记录身份降序稳定排序';
COMMENT ON COLUMN public."gfn_featured_site"."create_time" IS '导航精选网站与运营选取权重的记录创建时间';
COMMENT ON COLUMN public."gfn_featured_site"."update_time" IS '导航精选网站与运营选取权重的记录最近更新时间';

COMMENT ON TABLE public."gfn_home_hero_asset" IS '导航首页 Hero 素材目录；桌面和移动端是独立选取池，不按记录配对';
COMMENT ON COLUMN public."gfn_home_hero_asset"."id" IS '导航首页 Hero 素材目录的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_home_hero_asset"."variant" IS '素材所属池 desktop 或 mobile';
COMMENT ON COLUMN public."gfn_home_hero_asset"."name" IS '运营识别该素材的中文名称';
COMMENT ON COLUMN public."gfn_home_hero_asset"."object_key" IS 'Managed Asset Hero 对象键，形如 nav/hero/端类型/哈希.avif；不保存 CDN 域名';
COMMENT ON COLUMN public."gfn_home_hero_asset"."enabled" IS '是否允许该素材参与公开展示；删除状态另行约束';
COMMENT ON COLUMN public."gfn_home_hero_asset"."deleted" IS '是否已软删除；不代表已删除云端对象';
COMMENT ON COLUMN public."gfn_home_hero_asset"."deleted_at" IS '素材软删除的 UTC 时刻；未删除时为 NULL';
COMMENT ON COLUMN public."gfn_home_hero_asset"."create_time" IS '导航首页 Hero 素材目录的记录创建时间';
COMMENT ON COLUMN public."gfn_home_hero_asset"."update_time" IS '导航首页 Hero 素材目录的记录最近更新时间';

COMMENT ON TABLE public."gfn_metric_checkpoints" IS '网站指标各版本的独立有序水位；重建不能倒退该水位';
COMMENT ON COLUMN public."gfn_metric_checkpoints"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfn_metric_checkpoints"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfn_metric_checkpoints"."source_start_date" IS '可重建源证据的首个 UTC 日期；NULL 表示尚无起始证据';
COMMENT ON COLUMN public."gfn_metric_checkpoints"."processed_through" IS '已连续处理完成的最后一个 UTC 日期；NULL 表示尚未完成任何一天';
COMMENT ON COLUMN public."gfn_metric_checkpoints"."created_at" IS '网站指标各版本的独立有序水位的记录创建时间';
COMMENT ON COLUMN public."gfn_metric_checkpoints"."updated_at" IS '网站指标各版本的独立有序水位的记录最近更新时间';

COMMENT ON TABLE public."gfn_metric_daily" IS '网站指标每日全局及单维度状态计数；比例在查询时计算，不落最终百分比';
COMMENT ON COLUMN public."gfn_metric_daily"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfn_metric_daily"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfn_metric_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfn_metric_daily"."dimension_key" IS '汇总维度名；全局汇总使用 global，其它取注册合同允许的单维度';
COMMENT ON COLUMN public."gfn_metric_daily"."dimension_value" IS '该维度的历史取值；全局汇总使用 all';
COMMENT ON COLUMN public."gfn_metric_daily"."population_count" IS '实体总体数，等于 eligible_count + not_applicable_count';
COMMENT ON COLUMN public."gfn_metric_daily"."eligible_count" IS '适用实体数，等于除 not_applicable 外六种状态的计数之和';
COMMENT ON COLUMN public."gfn_metric_daily"."not_applicable_count" IS '不适用该指标的实体数，不进入适用分母';
COMMENT ON COLUMN public."gfn_metric_daily"."positive_count" IS '有明确正向证据的实体数，与 negative_count 共同组成已知分母';
COMMENT ON COLUMN public."gfn_metric_daily"."negative_count" IS '有明确反向证据的实体数；不能由未知或失败推断';
COMMENT ON COLUMN public."gfn_metric_daily"."stale_count" IS '证据已超过该版本新鲜度门槛的实体数';
COMMENT ON COLUMN public."gfn_metric_daily"."not_probed_count" IS '历史上尚未执行所需探测的实体数';
COMMENT ON COLUMN public."gfn_metric_daily"."probe_failed_count" IS '所需探测失败且不能得到有效判定的实体数';
COMMENT ON COLUMN public."gfn_metric_daily"."unknown_count" IS '证据不足以判定正反状态的实体数';
COMMENT ON COLUMN public."gfn_metric_daily"."computed_at" IS '本条派生结果最近一次计算完成的 UTC 时刻';

COMMENT ON TABLE public."gfn_metric_entity_daily" IS '网站实体每日可解释指标状态；仅从已 finalized 的历史事实产生';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."state" IS '七态结果 positive、negative、stale、not_probed、probe_failed、unknown、not_applicable；未知不能当作否定';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."reason_code" IS '解释该实体为何进入当前指标状态的稳定原因代码';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."source_observed_at" IS '来源证据的实际观察时刻；无可用证据时为 NULL，沿用证据不刷新此时刻';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."dimension_values" IS '该历史日的维度值 JSON 对象，不回查当前目录改写历史';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."source_projection_versions" IS '所用历史事实及其投影版本的 JSON 对象';
COMMENT ON COLUMN public."gfn_metric_entity_daily"."evaluated_at" IS '本次指标状态判定完成的 UTC 时刻';

COMMENT ON TABLE public."gfn_metric_registry" IS '网站指标版本注册合同；仅 Goose 修改，运行时和 Admin 只读';
COMMENT ON COLUMN public."gfn_metric_registry"."metric_key" IS '指标合同的稳定标识，与 metric_version 共同定位注册合同';
COMMENT ON COLUMN public."gfn_metric_registry"."metric_version" IS '指标语义版本；已发布版本不可原地改义';
COMMENT ON COLUMN public."gfn_metric_registry"."metric_kind" IS '指标类型；当前仅为 state_ratio，即按实体状态计算比例';
COMMENT ON COLUMN public."gfn_metric_registry"."entity_level" IS '指标实体层级；此库固定为 site';
COMMENT ON COLUMN public."gfn_metric_registry"."time_grain" IS '指标处理粒度；当前固定为 day，即 UTC 日';
COMMENT ON COLUMN public."gfn_metric_registry"."source_facts" IS '指标依赖的历史事实合同标识列表，不允许改用当前目录或原始采集替代';
COMMENT ON COLUMN public."gfn_metric_registry"."eligibility_policy" IS '判定实体是否属于指标适用总体的编译策略标识';
COMMENT ON COLUMN public."gfn_metric_registry"."state_policy" IS '由历史证据推导七态结果的编译策略标识';
COMMENT ON COLUMN public."gfn_metric_registry"."coverage_policy" IS '定义已知证据覆盖范围及统计分母的编译策略标识';
COMMENT ON COLUMN public."gfn_metric_registry"."freshness_seconds" IS '相对历史日结束时刻的证据有效秒数；NULL 表示无此新鲜度门槛';
COMMENT ON COLUMN public."gfn_metric_registry"."allowed_dimensions" IS '允许生成的单一维度名称列表；空列表表示仅全局汇总';
COMMENT ON COLUMN public."gfn_metric_registry"."status" IS '合同状态 active 或 retired；已退休版本仍可按原语义重建';
COMMENT ON COLUMN public."gfn_metric_registry"."description" IS '该指标版本的业务口径说明';
COMMENT ON COLUMN public."gfn_metric_registry"."created_at" IS '网站指标版本注册合同的记录创建时间';
COMMENT ON COLUMN public."gfn_metric_registry"."retired_at" IS '合同停止作为活跃版本的 UTC 时刻；active 时为 NULL';

COMMENT ON TABLE public."gfn_nav_update_notice" IS '导航更新公告；仅持久化草稿或已发布，未来发布时间决定定时展示';
COMMENT ON COLUMN public."gfn_nav_update_notice"."id" IS '导航更新公告的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_nav_update_notice"."title" IS '公告中文标题';
COMMENT ON COLUMN public."gfn_nav_update_notice"."title_en" IS '公告英文标题';
COMMENT ON COLUMN public."gfn_nav_update_notice"."body" IS '公告中文 Markdown 正文';
COMMENT ON COLUMN public."gfn_nav_update_notice"."body_en" IS '公告英文 Markdown 正文';
COMMENT ON COLUMN public."gfn_nav_update_notice"."published_at" IS '公告公开生效的 Asia/Shanghai 墙上时间；草稿可为 NULL，未来值表示定时发布';
COMMENT ON COLUMN public."gfn_nav_update_notice"."create_time" IS '导航更新公告的记录创建时间';
COMMENT ON COLUMN public."gfn_nav_update_notice"."update_time" IS '导航更新公告的记录最近更新时间';
COMMENT ON COLUMN public."gfn_nav_update_notice"."deleted" IS '公告软删除标记；公开查询排除已删除公告';
COMMENT ON COLUMN public."gfn_nav_update_notice"."version" IS '可选的产品发布版本文案，不是乐观并发版本';
COMMENT ON COLUMN public."gfn_nav_update_notice"."commit_sha" IS '可选的发布 Git 提交标识，7..64 位小写十六进制';
COMMENT ON COLUMN public."gfn_nav_update_notice"."summary" IS '公告中文列表摘要';
COMMENT ON COLUMN public."gfn_nav_update_notice"."summary_en" IS '公告英文列表摘要';
COMMENT ON COLUMN public."gfn_nav_update_notice"."publication_state" IS '持久发布状态 draft 或 published；scheduled 是时间派生状态，不入库';

COMMENT ON TABLE public."gfn_saying" IS '导航页按语言展示的金句内容';
COMMENT ON COLUMN public."gfn_saying"."id" IS '导航页按语言展示的金句内容的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_saying"."author" IS '金句作者或署名；未提供时为 NULL';
COMMENT ON COLUMN public."gfn_saying"."saying" IS '金句正文';
COMMENT ON COLUMN public."gfn_saying"."create_time" IS '导航页按语言展示的金句内容的记录创建时间';
COMMENT ON COLUMN public."gfn_saying"."update_time" IS '导航页按语言展示的金句内容的记录最近更新时间';
COMMENT ON COLUMN public."gfn_saying"."language" IS '金句展示语言 zh 或 en';

COMMENT ON TABLE public."gfn_site" IS '导航当前网站目录；软删除边界保留为历史事实的跟踪依据';
COMMENT ON COLUMN public."gfn_site"."id" IS '导航当前网站目录的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_site"."name" IS '运营维护的中文名称';
COMMENT ON COLUMN public."gfn_site"."name_en" IS '运营维护的英文名称';
COMMENT ON COLUMN public."gfn_site"."info" IS '运营维护的中文简介';
COMMENT ON COLUMN public."gfn_site"."info_en" IS '运营维护的英文简介';
COMMENT ON COLUMN public."gfn_site"."create_time" IS '导航当前网站目录的记录创建时间';
COMMENT ON COLUMN public."gfn_site"."update_time" IS '导航当前网站目录的记录最近更新时间';
COMMENT ON COLUMN public."gfn_site"."country" IS '网站所属国家或地区代码；未配置时为 NULL，不是探测 IP 地域';
COMMENT ON COLUMN public."gfn_site"."nsfw" IS '成人内容字符串标记，1 表示是、0 表示否；历史空值不推断为明确否';
COMMENT ON COLUMN public."gfn_site"."welfare" IS '公益属性字符串标记，1 表示是、0 表示否';
COMMENT ON COLUMN public."gfn_site"."icon" IS 'Managed Asset 网站图标对象键，如 nav/sites/网站身份/icon/哈希.扩展名；未配置时为 NULL';
COMMENT ON COLUMN public."gfn_site"."deleted" IS '网站软删除标记；删除与恢复维护对应历史资格边界';
COMMENT ON COLUMN public."gfn_site"."view_count" IS '网站入口累计访问计数，不是探测成功次数';
COMMENT ON COLUMN public."gfn_site"."deleted_at" IS '网站软删除的 UTC 边界；未删除时为 NULL，旧本地时间按 Asia/Shanghai 解释';

COMMENT ON TABLE public."gfn_site_daily" IS '网站每日历史维度和主目标快照；当前日可变，已完成历史日供指标读取';
COMMENT ON COLUMN public."gfn_site_daily"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_site_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfn_site_daily"."snapshot_at" IS '该行代表的历史快照时刻；不等同于原始证据观察时刻';
COMMENT ON COLUMN public."gfn_site_daily"."tracked_at_end" IS '在该事实日结束边界是否仍具跟踪资格';
COMMENT ON COLUMN public."gfn_site_daily"."name" IS '历史快照中的中文网站名称';
COMMENT ON COLUMN public."gfn_site_daily"."name_en" IS '历史快照中的英文网站名称';
COMMENT ON COLUMN public."gfn_site_daily"."site_country" IS '历史快照中的网站所属国家或地区；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_daily"."nsfw" IS '历史成人内容属性；无明确证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_daily"."welfare" IS '历史公益属性；无明确证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_daily"."view_count" IS '该历史快照的累计访问计数，不是当日增量';
COMMENT ON COLUMN public."gfn_site_daily"."group_ids" IS '历史快照中的网站分组身份集合，不回查当前关系改写';
COMMENT ON COLUMN public."gfn_site_daily"."primary_target_tracking_period_id" IS '该历史日有效主目标的跟踪区间身份；无主目标时为 NULL';
COMMENT ON COLUMN public."gfn_site_daily"."primary_target" IS '该历史日有效的主探测地址；无主目标时为 NULL';
COMMENT ON COLUMN public."gfn_site_daily"."primary_basis" IS '历史主目标的选择依据；无主目标时为 NULL';
COMMENT ON COLUMN public."gfn_site_daily"."active_target_count" IS '该快照时刻具有效跟踪资格的探测目标数量';
COMMENT ON COLUMN public."gfn_site_daily"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfn_site_daily"."finalized_at" IS '历史日投影完成的 UTC 时刻；当前日可变标记为 NULL';
COMMENT ON COLUMN public."gfn_site_daily"."created_at" IS '网站每日历史维度和主目标快照的记录创建时间';
COMMENT ON COLUMN public."gfn_site_daily"."updated_at" IS '网站每日历史维度和主目标快照的记录最近更新时间';

COMMENT ON TABLE public."gfn_site_group" IS '导航网站分组的当前运营内容与排序';
COMMENT ON COLUMN public."gfn_site_group"."id" IS '导航网站分组的当前运营内容与排序的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_site_group"."name" IS '运营维护的中文名称';
COMMENT ON COLUMN public."gfn_site_group"."name_en" IS '运营维护的英文名称';
COMMENT ON COLUMN public."gfn_site_group"."info" IS '运营维护的中文简介';
COMMENT ON COLUMN public."gfn_site_group"."info_en" IS '运营维护的英文简介';
COMMENT ON COLUMN public."gfn_site_group"."priority" IS '网站分组展示排序值，按升序排列；不是采集队列优先级';
COMMENT ON COLUMN public."gfn_site_group"."create_time" IS '导航网站分组的当前运营内容与排序的记录创建时间';
COMMENT ON COLUMN public."gfn_site_group"."update_time" IS '导航网站分组的当前运营内容与排序的记录最近更新时间';

COMMENT ON TABLE public."gfn_site_group_map" IS '网站与分组的当前归属关系及组内排序';
COMMENT ON COLUMN public."gfn_site_group_map"."id" IS '网站与分组的当前归属关系及组内排序的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_site_group_map"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_site_group_map"."group_id" IS '所属导航分组身份';
COMMENT ON COLUMN public."gfn_site_group_map"."create_time" IS '网站与分组的当前归属关系及组内排序的记录创建时间';
COMMENT ON COLUMN public."gfn_site_group_map"."update_time" IS '网站与分组的当前归属关系及组内排序的记录最近更新时间';
COMMENT ON COLUMN public."gfn_site_group_map"."weight" IS '网站在该分组中的运营排序权重，值越大越靠前';

COMMENT ON TABLE public."gfn_site_primary_target_periods" IS '网站主目标的有效时间区间；历史指标必须使用当时有效的主目标';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."id" IS '网站主目标的有效时间区间的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."target_tracking_period_id" IS '网站探测目标的历史跟踪区间身份，引用 gfn_target_tracking_periods';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."effective_from" IS '该主目标开始生效的 UTC 时刻，区间包含起点';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."effective_until" IS '该主目标停止生效的 UTC 时刻，区间不包含终点；NULL 表示仍有效';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."basis" IS '主目标选择依据 explicit、single_target_inferred、deterministic_fallback 或 legacy_backfill';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."created_at" IS '网站主目标的有效时间区间的记录创建时间';
COMMENT ON COLUMN public."gfn_site_primary_target_periods"."updated_at" IS '网站主目标的有效时间区间的记录最近更新时间';

COMMENT ON TABLE public."gfn_site_target_daily" IS '网站目标每日类型化 HTTP、TLS、DNS、Ping 已知事实；失败不能覆盖既有可用证据';
COMMENT ON COLUMN public."gfn_site_target_daily"."target_tracking_period_id" IS '网站探测目标的历史跟踪区间身份，引用 gfn_target_tracking_periods';
COMMENT ON COLUMN public."gfn_site_target_daily"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_site_target_daily"."collector_domain_id" IS '历史探测配置身份；无配置来源时为 NULL，不回查当前目录补写';
COMMENT ON COLUMN public."gfn_site_target_daily"."target" IS '该事实所属历史跟踪区间的探测地址';
COMMENT ON COLUMN public."gfn_site_target_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfn_site_target_daily"."snapshot_at" IS '该行代表的历史快照时刻；不等同于原始证据观察时刻';
COMMENT ON COLUMN public."gfn_site_target_daily"."tracked_at_end" IS '在该事实日结束边界是否仍具跟踪资格';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_probe_status" IS '最近 HTTP 探测结果；无探测时为 NULL，不等同于最后已知能力状态';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_probe_observed_at" IS '最近 HTTP 探测的观察时刻；无探测时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_state_observed_at" IS '最后可用 HTTP 状态的实际观察时刻；沿用证据不刷新，未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_status_code" IS '最后已知 HTTP 响应状态码；无有效证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_response_time_ms" IS '最后已知 HTTP 响应耗时，单位毫秒；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_ttfb_ms" IS '最后已知 HTTP 首字节耗时，单位毫秒；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_protocol" IS '最后已知 HTTP 协议版本；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_server" IS '最后已知 HTTP Server 响应头；未取得时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_remote_ip" IS '最后已知 HTTP 实际连接的远端地址；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_final_url" IS '最后已知 HTTP 跟随重定向后的最终 URL；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_canonical_url" IS '最后已知页面声明的 canonical URL；未取得时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."http_security_headers" IS '最后已知 HTTP 安全响应头的白名单 JSON；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_state_observed_at" IS 'TLS 已知证据的原始观察时刻；来自 HTTP 状态，沿用不刷新';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_handshake" IS '最后已知 TLS 握手结果；无证据时为 NULL，不代替证书验证状态';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_version" IS '成功握手证据中的 TLS 版本；无有效证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cipher_suite" IS '握手证据中的 TLS 密码套件；无有效证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cert_verified" IS '证书链是否通过验证；未能验证时为 NULL，不能把握手失败当作明确否';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_verify_error_category" IS '证书验证失败的规范分类；无对应证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cert_not_before" IS '证书有效期的 UTC 起点；源时间无效或未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cert_not_after" IS '证书有效期的 UTC 终点；源时间无效或未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cert_issuer" IS '最后已知证书的颁发者；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cert_fingerprint_sha256" IS '最后已知叶证书的 SHA256 指纹；用于证书变化检测，未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cert_spki_sha256" IS '最后已知证书公钥 SPKI 的 SHA256 摘要；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."tls_cert_dns_names" IS '最后已知证书包含的 DNS 名称集合；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_probe_status" IS '最近 DNS 探测结果；无探测时为 NULL，不等同于最后已知能力状态';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_probe_observed_at" IS '最近 DNS 探测的观察时刻；无探测时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_state_observed_at" IS '最后可用 DNS 状态的实际观察时刻；沿用证据不刷新，未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_has_a" IS '已知 DNS 状态是否含 A 记录；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_has_aaaa" IS '已知 DNS 状态是否含 AAAA 记录；查询失败不能据此推断不支持，V2 指标另核对查询证据';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_ipv4_count" IS '已知 DNS A 地址数；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_ipv6_count" IS '已知 DNS AAAA 地址数；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_a_records" IS '最后已知 DNS A 地址集合；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_aaaa_records" IS '最后已知 DNS AAAA 地址集合；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_cname_terminal" IS '已知 CNAME 链的终点名称；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_cname_depth" IS '已知 CNAME 链的跳数；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_ns_hosts" IS '最后已知 DNS NS 主机集合；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_mx_hosts" IS '最后已知 DNS MX 主机集合；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_min_ttl" IS '已知 DNS 记录的最小 TTL 秒数；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_max_ttl" IS '已知 DNS 记录的最大 TTL 秒数；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."dns_risk_flags" IS '最后已知 DNS 风险标记集合；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_probe_status" IS '最近 PING 探测结果；无探测时为 NULL，不等同于最后已知能力状态';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_probe_observed_at" IS '最近 PING 探测的观察时刻；无探测时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_state_observed_at" IS '最后可用 PING 状态的实际观察时刻；沿用证据不刷新，未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_avg_rtt_ms" IS '最后已知 Ping 平均往返耗时毫秒数；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_min_rtt_ms" IS '最后已知 Ping 最小往返耗时毫秒数；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_max_rtt_ms" IS '最后已知 Ping 最大往返耗时毫秒数；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_loss_rate" IS '最后已知 Ping 丢包百分比，100 表示全部丢包；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_jitter_ms" IS '最后已知 Ping 抖动，单位毫秒；无证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_selected_ip" IS '最后已知 Ping 实际选择的目标地址；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_ip_family" IS '最后已知 Ping 目标的 IP 协议族；未知时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_daily"."ping_icmp_blocked_suspected" IS '探测是否怀疑 ICMP 被阻断；无证据时为 NULL，不等同于网站不可用';
COMMENT ON COLUMN public."gfn_site_target_daily"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfn_site_target_daily"."finalized_at" IS '该历史日事实投影完成的 UTC 时刻';
COMMENT ON COLUMN public."gfn_site_target_daily"."created_at" IS '网站目标每日类型化 HTTP、TLS、DNS、Ping 已知事实的记录创建时间';
COMMENT ON COLUMN public."gfn_site_target_daily"."updated_at" IS '网站目标每日类型化 HTTP、TLS、DNS、Ping 已知事实的记录最近更新时间';

COMMENT ON TABLE public."gfn_site_target_protocol_daily" IS '目标各协议每日计划质量、最近观察结果和白名单内的最后已知状态；三者不可混同';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."target_tracking_period_id" IS '网站探测目标的历史跟踪区间身份，引用 gfn_target_tracking_periods';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."collector_domain_id" IS '历史探测配置身份；无配置来源时为 NULL，不回查当前目录补写';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."target" IS '该事实所属历史跟踪区间的探测地址';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."protocol" IS '此行聚合的探测协议，同一目标每日各协议分别保存';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."fact_date" IS '该历史事实或指标所属的 UTC 日期';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."expected_count" IS '计划账本应有探测次数；旧观察无完整账本时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."attempted_count" IS '实际尝试次数，等于 success_count + partial_count + failure_count';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."success_count" IS '计划探测完整成功次数';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."partial_count" IS '计划探测部分成功次数';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."failure_count" IS '计划探测执行失败次数';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."skipped_count" IS '计划账本记录跳过的次数；无完整账本时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."missed_count" IS '计划账本记录错过的次数；无完整账本时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."canceled_count" IS '计划账本记录取消的次数；无完整账本时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."unattempted_count" IS '计划存在但没有执行尝试的次数；无完整账本时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."failure_kind_counts" IS '按失败类别汇总的次数 JSON 对象；与成功样本数分开解释';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."quality_basis" IS '质量分母依据：legacy_observed_only 只有历史观察，acquisition_ledger 才有完整计划账本';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."latest_scheduled_status" IS '当日最近计划探测的执行结果；无计划结果时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."latest_scheduled_at" IS '当日最近计划探测的槽位时刻；无计划时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."latest_observation_status" IS '截至该日最近原始观察的结果，可能来自手动探测；无观察时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."latest_observation_at" IS '截至该日最近原始观察的时刻；无观察时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."known_state_observed_at" IS '最后可用协议状态的原始观察时刻；沿用证据不刷新，无已知状态时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."known_state" IS '白名单内的最后已知协议证据 JSON；不是完整 payload，无有效证据时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."avg_duration_ms" IS '该日计划探测已尝试执行的耗时均值，单位毫秒；无样本时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."p95_duration_ms" IS '该日计划探测已尝试执行耗时的第 95 百分位，单位毫秒；无样本时为 NULL';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."projection_version" IS '历史事实投影的语义版本；用于解释和校验下游证据';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."finalized_at" IS '该历史日事实投影完成的 UTC 时刻';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."created_at" IS '目标各协议每日计划质量、最近观察结果和白名单内的最后已知状态的记录创建时间';
COMMENT ON COLUMN public."gfn_site_target_protocol_daily"."updated_at" IS '目标各协议每日计划质量、最近观察结果和白名单内的最后已知状态的记录最近更新时间';

COMMENT ON TABLE public."gfn_target_tracking_periods" IS '网站探测目标的历史跟踪资格区间；当前目录删除不抹除历史身份';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."id" IS '网站探测目标的历史跟踪资格区间的行身份；用于稳定引用该记录';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."collector_domain_id" IS '建立区间时的探测配置身份；历史推断可为 NULL，不依赖当前配置外键';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."site_id" IS 'GoFurry 网站身份；与探测目标域名分别保存';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."target" IS '该历史区间内稳定的探测目标地址';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."tracked_from" IS '跟踪资格生效的 UTC 时刻，区间包含此起点';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."tracked_until" IS '跟踪资格失效的 UTC 时刻，区间不包含此终点；NULL 表示仍在跟踪';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."tracking_basis" IS '区间依据 explicit 明确配置或 legacy_observed 历史观察推断';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."opened_reason" IS '建立该历史跟踪区间的业务原因';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."closed_reason" IS '关闭该历史跟踪区间的业务原因；未关闭时为 NULL';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."created_at" IS '网站探测目标的历史跟踪资格区间的记录创建时间';
COMMENT ON COLUMN public."gfn_target_tracking_periods"."updated_at" IS '网站探测目标的历史跟踪资格区间的记录最近更新时间';

COMMENT ON FUNCTION public.gfn_jsonb_text_array(value jsonb) IS '将 JSON 数组转换为文本数组；非数组或缺失值返回 NULL，以保留未知证据语义';
COMMENT ON FUNCTION public.gfn_project_change_day(target_detector_key text, target_detector_version integer, target_date date) IS '按检测器及版本重建指定 UTC 日的 V1 网站规范变化事件；保留历史语义记忆及主目标区间边界，返回写入条数';
COMMENT ON FUNCTION public.gfn_project_change_day_v2(target_detector_key text, target_detector_version integer, target_date date) IS '重建指定 UTC 日的 V2 IPv6 或 security.txt 变化事件，严格使用 V2 证据合同；返回写入条数，不覆盖 V1 历史语义';
COMMENT ON FUNCTION public.gfn_project_metric_day(target_metric_key text, target_metric_version integer, target_date date) IS '按指标及版本重建指定 UTC 日的 V1 IPv6、TLS 1.3 或 security.txt 指标；保留原版本重建口径，返回实体条数';
COMMENT ON FUNCTION public.gfn_project_metric_day_v2(target_metric_key text, target_metric_version integer, target_date date) IS '重建指定 UTC 日的 V2 IPv6 或 security.txt 指标，明确区分失败、未知与否定证据；返回实体条数';
COMMENT ON FUNCTION public.gfn_project_site_capability_change_day(target_detector_key text, target_detector_version integer, target_date date) IS '重建指定 UTC 日的网站 HTTP/2、HSTS、CSP 或证书验证变化；在同一历史主目标内维护语义记忆，返回写入条数';
COMMENT ON FUNCTION public.gfn_project_site_capability_metric_day(target_metric_key text, target_metric_version integer, target_date date) IS '从 finalized 历史事实重建指定 UTC 日的 HTTP/2、HSTS、CSP 或证书验证指标实体与计数；返回实体条数';
COMMENT ON FUNCTION public.gfn_project_site_fact_day(target_date date) IS '投影指定 UTC 日的网站历史维度和有效主目标，完成历史日事实并返回写入条数；水位由调用事务维护';
COMMENT ON FUNCTION public.gfn_project_target_fact_day(target_date date) IS '从协议已知状态投影指定 UTC 日的目标类型化事实；未知保留 NULL，无效证书时间不伪造；返回写入条数';
COMMENT ON FUNCTION public.gfn_prune_observations_batch(target_keep_count integer, target_batch_size integer) IS '在 nav.target_facts 已处理水位内按网站、目标、协议保留最新指定条数并分批裁剪原始观察；无水位或非法参数删除零条，返回删除数';
COMMENT ON FUNCTION public.gfn_refresh_current_site_daily(target_site_id bigint) IS '为指定网站刷新当前 UTC 日的可变历史维度及有效主目标，finalized_at 为 NULL；不回写已结束历史日';
