// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCollectionMemberships = `-- name: BatchCollectionMemberships :many
SELECT collection_id, game_id FROM gfg_game_collection_item
WHERE collection_id = ANY($1::bigint[])
ORDER BY collection_id, game_id
`

type BatchCollectionMembershipsRow struct {
	CollectionID int64 `json:"collection_id"`
	GameID       int64 `json:"game_id"`
}

func (q *Queries) BatchCollectionMemberships(ctx context.Context, collectionIds []int64) ([]BatchCollectionMembershipsRow, error) {
	rows, err := q.db.Query(ctx, batchCollectionMemberships, collectionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchCollectionMembershipsRow{}
	for rows.Next() {
		var i BatchCollectionMembershipsRow
		if err := rows.Scan(&i.CollectionID, &i.GameID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPublishedCollections = `-- name: CountPublishedCollections :one
SELECT count(*) FROM gfg_game_collection WHERE status = 'published'
`

func (q *Queries) CountPublishedCollections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedCollections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublishedCollection = `-- name: GetPublishedCollection :one
SELECT id, code, name, name_en, info, info_en, published_at
FROM gfg_game_collection WHERE code = $1 AND status = 'published'
`

type GetPublishedCollectionRow struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	NameEn      string             `json:"name_en"`
	Info        string             `json:"info"`
	InfoEn      string             `json:"info_en"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetPublishedCollection(ctx context.Context, code string) (GetPublishedCollectionRow, error) {
	row := q.db.QueryRow(ctx, getPublishedCollection, code)
	var i GetPublishedCollectionRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.NameEn,
		&i.Info,
		&i.InfoEn,
		&i.PublishedAt,
	)
	return i, err
}

const listPublishedCollectionHomeSlots = `-- name: ListPublishedCollectionHomeSlots :many
SELECT s.slot, c.id, c.code, c.name, c.name_en, c.info, c.info_en, c.published_at
FROM gfg_game_collection_home_slot s
JOIN gfg_game_collection c ON c.id = s.collection_id
WHERE c.status = 'published'
ORDER BY s.slot
`

type ListPublishedCollectionHomeSlotsRow struct {
	Slot        int16              `json:"slot"`
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	NameEn      string             `json:"name_en"`
	Info        string             `json:"info"`
	InfoEn      string             `json:"info_en"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPublishedCollectionHomeSlots(ctx context.Context) ([]ListPublishedCollectionHomeSlotsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedCollectionHomeSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedCollectionHomeSlotsRow{}
	for rows.Next() {
		var i ListPublishedCollectionHomeSlotsRow
		if err := rows.Scan(
			&i.Slot,
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NameEn,
			&i.Info,
			&i.InfoEn,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCollections = `-- name: ListPublishedCollections :many
SELECT id, code, name, name_en, info, info_en, published_at
FROM gfg_game_collection WHERE status = 'published'
ORDER BY published_at DESC, id DESC
LIMIT $2::bigint OFFSET $1::bigint
`

type ListPublishedCollectionsParams struct {
	PageOffset int64 `json:"page_offset"`
	PageSize   int64 `json:"page_size"`
}

type ListPublishedCollectionsRow struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	NameEn      string             `json:"name_en"`
	Info        string             `json:"info"`
	InfoEn      string             `json:"info_en"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ListPublishedCollections(ctx context.Context, arg ListPublishedCollectionsParams) ([]ListPublishedCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedCollections, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedCollectionsRow{}
	for rows.Next() {
		var i ListPublishedCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.NameEn,
			&i.Info,
			&i.InfoEn,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
