// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: showcase.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listShowcaseGames = `-- name: ListShowcaseGames :many
SELECT g.id,g.appid,g.showcase_eligible,
 CASE WHEN $1::text='en' THEN g.name_en ELSE g.name END::text AS title,
 CASE WHEN $1::text='en' THEN g.info_en ELSE g.info END::text AS summary,
 COALESCE((SELECT a.url FROM gfg_game_assets a WHERE a.game_id=g.id AND a.appid=g.appid
   AND a.asset_type IN ('header','header_2x') AND btrim(a.url)<>'' AND a.exists IS DISTINCT FROM false
   ORDER BY CASE a.asset_type WHEN 'header' THEN 0 ELSE 1 END,
     CASE WHEN a.lang=$1::text THEN 0 WHEN a.lang<>'' THEN 1 ELSE 2 END,a.sort_order,a.id LIMIT 1),
   (SELECT NULLIF(m.url,'') FROM gfg_game_media m WHERE m.game_id=g.id AND m.appid=g.appid AND m.media_type='header'
     ORDER BY m.sort_order DESC,m.id DESC LIMIT 1),NULLIF(d.header_url,''),NULLIF(g.header,''),'')::text AS artwork_url,
 NOT EXISTS(SELECT 1 FROM gfg_game_tag m JOIN gfg_tag t ON t.id=m.tag_id
   WHERE m.game_id=g.id AND t.code='adult')::boolean AS sfw,
 ARRAY(SELECT CASE WHEN $1::text='en' THEN t.name_en ELSE t.name END::text
   FROM gfg_game_tag m JOIN gfg_tag t ON t.id=m.tag_id WHERE m.game_id=g.id
   ORDER BY CASE m.role WHEN 'primary' THEN 0 WHEN 'secondary' THEN 1 ELSE 2 END,t.id LIMIT 3)::text[] AS tags,
 r.availability,r.precision,r.exact_date,r.release_year,r.release_month,r.release_quarter,r.window_start,r.window_end,
 COALESCE(f.exact_date,f.window_start)::date AS first_available,
 p.id AS tracking_period_id
FROM gfg_game g
LEFT JOIN gfg_game_details d ON d.game_id=g.id AND d.appid=g.appid
LEFT JOIN gfg_game_release_state r ON r.game_id=g.id
LEFT JOIN gfg_game_first_available f ON f.game_id=g.id
LEFT JOIN gfg_game_tracking_periods p ON p.game_id=g.id AND p.appid=g.appid AND p.tracking_basis='explicit' AND p.tracked_until IS NULL
ORDER BY g.id
`

type ListShowcaseGamesRow struct {
	ID               int64       `json:"id"`
	Appid            int64       `json:"appid"`
	ShowcaseEligible bool        `json:"showcase_eligible"`
	Title            string      `json:"title"`
	Summary          string      `json:"summary"`
	ArtworkUrl       string      `json:"artwork_url"`
	Sfw              *bool       `json:"sfw"`
	Tags             []string    `json:"tags"`
	Availability     *string     `json:"availability"`
	Precision        *string     `json:"precision"`
	ExactDate        pgtype.Date `json:"exact_date"`
	ReleaseYear      *int32      `json:"release_year"`
	ReleaseMonth     *int32      `json:"release_month"`
	ReleaseQuarter   *int32      `json:"release_quarter"`
	WindowStart      pgtype.Date `json:"window_start"`
	WindowEnd        pgtype.Date `json:"window_end"`
	FirstAvailable   pgtype.Date `json:"first_available"`
	TrackingPeriodID *int64      `json:"tracking_period_id"`
}

func (q *Queries) ListShowcaseGames(ctx context.Context, lang string) ([]ListShowcaseGamesRow, error) {
	rows, err := q.db.Query(ctx, listShowcaseGames, lang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowcaseGamesRow{}
	for rows.Next() {
		var i ListShowcaseGamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Appid,
			&i.ShowcaseEligible,
			&i.Title,
			&i.Summary,
			&i.ArtworkUrl,
			&i.Sfw,
			&i.Tags,
			&i.Availability,
			&i.Precision,
			&i.ExactDate,
			&i.ReleaseYear,
			&i.ReleaseMonth,
			&i.ReleaseQuarter,
			&i.WindowStart,
			&i.WindowEnd,
			&i.FirstAvailable,
			&i.TrackingPeriodID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowcaseManaged = `-- name: ListShowcaseManaged :many
SELECT c.id, c.internal_name, c.content_type, c.sponsored, c.linked_game_id, c.state, c.starts_at, c.ends_at, c.weight, c.pin_position, c.desktop_object_key, c.mobile_object_key, c.focal_x, c.focal_y, c.primary_action_type, c.primary_target, c.secondary_action_type, c.secondary_target, c.created_at, c.updated_at,l.campaign_id, l.lang, l.enabled, l.title, l.summary, l.tags, l.editorial_note, l.created_at, l.updated_at,
 (c.linked_game_id IS NULL OR EXISTS(SELECT 1 FROM gfg_game g WHERE g.id=c.linked_game_id))::boolean AS game_exists,
 NOT EXISTS(SELECT 1 FROM gfg_game_tag m JOIN gfg_tag t ON t.id=m.tag_id
   WHERE m.game_id=c.linked_game_id AND t.code='adult')::boolean AS sfw
FROM gfg_showcase_campaign c JOIN gfg_showcase_campaign_locale l ON l.campaign_id=c.id
WHERE c.state='published' AND l.enabled AND l.lang=$1
 AND c.starts_at<=$2::timestamptz AND c.ends_at>$2::timestamptz ORDER BY c.id
`

type ListShowcaseManagedParams struct {
	Lang   string             `json:"lang"`
	AtTime pgtype.Timestamptz `json:"at_time"`
}

type ListShowcaseManagedRow struct {
	GfgShowcaseCampaign       GfgShowcaseCampaign       `json:"gfg_showcase_campaign"`
	GfgShowcaseCampaignLocale GfgShowcaseCampaignLocale `json:"gfg_showcase_campaign_locale"`
	GameExists                bool                      `json:"game_exists"`
	Sfw                       *bool                     `json:"sfw"`
}

func (q *Queries) ListShowcaseManaged(ctx context.Context, arg ListShowcaseManagedParams) ([]ListShowcaseManagedRow, error) {
	rows, err := q.db.Query(ctx, listShowcaseManaged, arg.Lang, arg.AtTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowcaseManagedRow{}
	for rows.Next() {
		var i ListShowcaseManagedRow
		if err := rows.Scan(
			&i.GfgShowcaseCampaign.ID,
			&i.GfgShowcaseCampaign.InternalName,
			&i.GfgShowcaseCampaign.ContentType,
			&i.GfgShowcaseCampaign.Sponsored,
			&i.GfgShowcaseCampaign.LinkedGameID,
			&i.GfgShowcaseCampaign.State,
			&i.GfgShowcaseCampaign.StartsAt,
			&i.GfgShowcaseCampaign.EndsAt,
			&i.GfgShowcaseCampaign.Weight,
			&i.GfgShowcaseCampaign.PinPosition,
			&i.GfgShowcaseCampaign.DesktopObjectKey,
			&i.GfgShowcaseCampaign.MobileObjectKey,
			&i.GfgShowcaseCampaign.FocalX,
			&i.GfgShowcaseCampaign.FocalY,
			&i.GfgShowcaseCampaign.PrimaryActionType,
			&i.GfgShowcaseCampaign.PrimaryTarget,
			&i.GfgShowcaseCampaign.SecondaryActionType,
			&i.GfgShowcaseCampaign.SecondaryTarget,
			&i.GfgShowcaseCampaign.CreatedAt,
			&i.GfgShowcaseCampaign.UpdatedAt,
			&i.GfgShowcaseCampaignLocale.CampaignID,
			&i.GfgShowcaseCampaignLocale.Lang,
			&i.GfgShowcaseCampaignLocale.Enabled,
			&i.GfgShowcaseCampaignLocale.Title,
			&i.GfgShowcaseCampaignLocale.Summary,
			&i.GfgShowcaseCampaignLocale.Tags,
			&i.GfgShowcaseCampaignLocale.EditorialNote,
			&i.GfgShowcaseCampaignLocale.CreatedAt,
			&i.GfgShowcaseCampaignLocale.UpdatedAt,
			&i.GameExists,
			&i.Sfw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowcasePlayerFacts = `-- name: ListShowcasePlayerFacts :many
SELECT d.tracking_period_id,d.game_id,d.fact_date,d.avg_players,d.successful_samples,d.expected_samples,d.quality_basis,
 h.processed_through
FROM gfg_fact_rollup_checkpoints h
JOIN gfg_game_tracking_periods p ON p.tracking_basis='explicit' AND p.tracked_until IS NULL
JOIN gfg_game g ON g.id=p.game_id AND g.appid=p.appid
JOIN gfg_game_player_daily d ON d.tracking_period_id=p.id AND d.game_id=g.id AND d.appid=g.appid
WHERE h.pipeline_key='game.player_facts' AND d.finalized_at IS NOT NULL
 AND d.fact_date BETWEEN h.processed_through-9 AND h.processed_through
 AND d.fact_date >= (p.tracked_from AT TIME ZONE 'UTC')::date
ORDER BY d.tracking_period_id,d.fact_date
`

type ListShowcasePlayerFactsRow struct {
	TrackingPeriodID  int64       `json:"tracking_period_id"`
	GameID            int64       `json:"game_id"`
	FactDate          pgtype.Date `json:"fact_date"`
	AvgPlayers        *float64    `json:"avg_players"`
	SuccessfulSamples int32       `json:"successful_samples"`
	ExpectedSamples   *int32      `json:"expected_samples"`
	QualityBasis      string      `json:"quality_basis"`
	ProcessedThrough  pgtype.Date `json:"processed_through"`
}

func (q *Queries) ListShowcasePlayerFacts(ctx context.Context) ([]ListShowcasePlayerFactsRow, error) {
	rows, err := q.db.Query(ctx, listShowcasePlayerFacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowcasePlayerFactsRow{}
	for rows.Next() {
		var i ListShowcasePlayerFactsRow
		if err := rows.Scan(
			&i.TrackingPeriodID,
			&i.GameID,
			&i.FactDate,
			&i.AvgPlayers,
			&i.SuccessfulSamples,
			&i.ExpectedSamples,
			&i.QualityBasis,
			&i.ProcessedThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextShowcaseBoundary = `-- name: NextShowcaseBoundary :one
SELECT min(boundary)::timestamptz FROM (
 SELECT c.starts_at AS boundary FROM gfg_showcase_campaign c JOIN gfg_showcase_campaign_locale l ON l.campaign_id=c.id
 WHERE c.state='published' AND l.enabled AND l.lang=$1 AND c.starts_at>$2::timestamptz
 UNION ALL
 SELECT c.ends_at FROM gfg_showcase_campaign c JOIN gfg_showcase_campaign_locale l ON l.campaign_id=c.id
 WHERE c.state='published' AND l.enabled AND l.lang=$1 AND c.ends_at>$2::timestamptz
) boundaries
`

type NextShowcaseBoundaryParams struct {
	Lang   string             `json:"lang"`
	AtTime pgtype.Timestamptz `json:"at_time"`
}

func (q *Queries) NextShowcaseBoundary(ctx context.Context, arg NextShowcaseBoundaryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, nextShowcaseBoundary, arg.Lang, arg.AtTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertShowcaseDailyStat = `-- name: UpsertShowcaseDailyStat :exec
INSERT INTO gfg_showcase_daily_stat(stat_date,subject_key,subject_kind,campaign_id,game_id,reason,
 valid_impressions,qualified_clicks,click_artwork,click_title,click_primary,click_secondary,
 impression_position_1,impression_position_2,impression_position_3,impression_position_4,session_estimate)
VALUES($1,$2,$3,$4,$5,$6,
 $7,$8,$9,$10,$11,$12,
 $13,$14,$15,$16,$17)
ON CONFLICT(stat_date,subject_key) DO UPDATE SET
 valid_impressions=EXCLUDED.valid_impressions,qualified_clicks=EXCLUDED.qualified_clicks,
 click_artwork=EXCLUDED.click_artwork,click_title=EXCLUDED.click_title,click_primary=EXCLUDED.click_primary,click_secondary=EXCLUDED.click_secondary,
 impression_position_1=EXCLUDED.impression_position_1,impression_position_2=EXCLUDED.impression_position_2,
 impression_position_3=EXCLUDED.impression_position_3,impression_position_4=EXCLUDED.impression_position_4,
 session_estimate=EXCLUDED.session_estimate,updated_at=now()
WHERE gfg_showcase_daily_stat.valid_impressions<=EXCLUDED.valid_impressions
 AND gfg_showcase_daily_stat.qualified_clicks<=EXCLUDED.qualified_clicks
`

type UpsertShowcaseDailyStatParams struct {
	StatDate            pgtype.Date `json:"stat_date"`
	SubjectKey          string      `json:"subject_key"`
	SubjectKind         string      `json:"subject_kind"`
	CampaignID          *int64      `json:"campaign_id"`
	GameID              *int64      `json:"game_id"`
	Reason              string      `json:"reason"`
	ValidImpressions    int64       `json:"valid_impressions"`
	QualifiedClicks     int64       `json:"qualified_clicks"`
	ClickArtwork        int64       `json:"click_artwork"`
	ClickTitle          int64       `json:"click_title"`
	ClickPrimary        int64       `json:"click_primary"`
	ClickSecondary      int64       `json:"click_secondary"`
	ImpressionPosition1 int64       `json:"impression_position_1"`
	ImpressionPosition2 int64       `json:"impression_position_2"`
	ImpressionPosition3 int64       `json:"impression_position_3"`
	ImpressionPosition4 int64       `json:"impression_position_4"`
	SessionEstimate     int64       `json:"session_estimate"`
}

func (q *Queries) UpsertShowcaseDailyStat(ctx context.Context, arg UpsertShowcaseDailyStatParams) error {
	_, err := q.db.Exec(ctx, upsertShowcaseDailyStat,
		arg.StatDate,
		arg.SubjectKey,
		arg.SubjectKind,
		arg.CampaignID,
		arg.GameID,
		arg.Reason,
		arg.ValidImpressions,
		arg.QualifiedClicks,
		arg.ClickArtwork,
		arg.ClickTitle,
		arg.ClickPrimary,
		arg.ClickSecondary,
		arg.ImpressionPosition1,
		arg.ImpressionPosition2,
		arg.ImpressionPosition3,
		arg.ImpressionPosition4,
		arg.SessionEstimate,
	)
	return err
}

const upsertShowcaseQuality = `-- name: UpsertShowcaseQuality :exec
INSERT INTO gfg_showcase_analytics_daily_quality(stat_date,invalid_token_events,invalid_origin_events,filtered_user_agent_events,
 duplicate_impressions,duplicate_clicks,session_rate_limited,ip_rate_limited,malformed_events)
VALUES($1,$2,$3,$4,
 $5,$6,$7,$8,$9)
ON CONFLICT(stat_date) DO UPDATE SET invalid_token_events=GREATEST(gfg_showcase_analytics_daily_quality.invalid_token_events,EXCLUDED.invalid_token_events),
 invalid_origin_events=GREATEST(gfg_showcase_analytics_daily_quality.invalid_origin_events,EXCLUDED.invalid_origin_events),
 filtered_user_agent_events=GREATEST(gfg_showcase_analytics_daily_quality.filtered_user_agent_events,EXCLUDED.filtered_user_agent_events),
 duplicate_impressions=GREATEST(gfg_showcase_analytics_daily_quality.duplicate_impressions,EXCLUDED.duplicate_impressions),
 duplicate_clicks=GREATEST(gfg_showcase_analytics_daily_quality.duplicate_clicks,EXCLUDED.duplicate_clicks),
 session_rate_limited=GREATEST(gfg_showcase_analytics_daily_quality.session_rate_limited,EXCLUDED.session_rate_limited),
 ip_rate_limited=GREATEST(gfg_showcase_analytics_daily_quality.ip_rate_limited,EXCLUDED.ip_rate_limited),
 malformed_events=GREATEST(gfg_showcase_analytics_daily_quality.malformed_events,EXCLUDED.malformed_events),updated_at=now()
`

type UpsertShowcaseQualityParams struct {
	StatDate                pgtype.Date `json:"stat_date"`
	InvalidTokenEvents      int64       `json:"invalid_token_events"`
	InvalidOriginEvents     int64       `json:"invalid_origin_events"`
	FilteredUserAgentEvents int64       `json:"filtered_user_agent_events"`
	DuplicateImpressions    int64       `json:"duplicate_impressions"`
	DuplicateClicks         int64       `json:"duplicate_clicks"`
	SessionRateLimited      int64       `json:"session_rate_limited"`
	IpRateLimited           int64       `json:"ip_rate_limited"`
	MalformedEvents         int64       `json:"malformed_events"`
}

func (q *Queries) UpsertShowcaseQuality(ctx context.Context, arg UpsertShowcaseQualityParams) error {
	_, err := q.db.Exec(ctx, upsertShowcaseQuality,
		arg.StatDate,
		arg.InvalidTokenEvents,
		arg.InvalidOriginEvents,
		arg.FilteredUserAgentEvents,
		arg.DuplicateImpressions,
		arg.DuplicateClicks,
		arg.SessionRateLimited,
		arg.IpRateLimited,
		arg.MalformedEvents,
	)
	return err
}
