// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: showcase.sql

package gamesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countShowcaseCampaigns = `-- name: CountShowcaseCampaigns :one
SELECT count(*)::bigint FROM gfg_showcase_campaign c
WHERE ($1::text='' OR c.state=$1)
 AND ($2::boolean IS NULL OR c.sponsored=$2)
 AND ($3::text='' OR c.internal_name ILIKE '%'||$3||'%' OR c.id::text=$3)
 AND ($4::text='' OR CASE WHEN c.state<>'published' THEN c.state
      WHEN $5::timestamptz<c.starts_at THEN 'scheduled'
      WHEN $5::timestamptz>=c.ends_at THEN 'ended' ELSE 'active' END=$4)
`

type CountShowcaseCampaignsParams struct {
	State         string             `json:"state"`
	Sponsored     *bool              `json:"sponsored"`
	Keyword       string             `json:"keyword"`
	DerivedStatus string             `json:"derived_status"`
	AtTime        pgtype.Timestamptz `json:"at_time"`
}

func (q *Queries) CountShowcaseCampaigns(ctx context.Context, arg CountShowcaseCampaignsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countShowcaseCampaigns,
		arg.State,
		arg.Sponsored,
		arg.Keyword,
		arg.DerivedStatus,
		arg.AtTime,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createShowcaseCampaign = `-- name: CreateShowcaseCampaign :one
INSERT INTO gfg_showcase_campaign(internal_name,content_type,sponsored,linked_game_id)
VALUES ($1,$2,$3,$4) RETURNING id, internal_name, content_type, sponsored, linked_game_id, state, starts_at, ends_at, weight, pin_position, desktop_object_key, mobile_object_key, focal_x, focal_y, primary_action_type, primary_target, secondary_action_type, secondary_target, created_at, updated_at
`

type CreateShowcaseCampaignParams struct {
	InternalName string `json:"internal_name"`
	ContentType  string `json:"content_type"`
	Sponsored    bool   `json:"sponsored"`
	LinkedGameID *int64 `json:"linked_game_id"`
}

func (q *Queries) CreateShowcaseCampaign(ctx context.Context, arg CreateShowcaseCampaignParams) (GfgShowcaseCampaign, error) {
	row := q.db.QueryRow(ctx, createShowcaseCampaign,
		arg.InternalName,
		arg.ContentType,
		arg.Sponsored,
		arg.LinkedGameID,
	)
	var i GfgShowcaseCampaign
	err := row.Scan(
		&i.ID,
		&i.InternalName,
		&i.ContentType,
		&i.Sponsored,
		&i.LinkedGameID,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.Weight,
		&i.PinPosition,
		&i.DesktopObjectKey,
		&i.MobileObjectKey,
		&i.FocalX,
		&i.FocalY,
		&i.PrimaryActionType,
		&i.PrimaryTarget,
		&i.SecondaryActionType,
		&i.SecondaryTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShowcaseDraft = `-- name: DeleteShowcaseDraft :execrows
DELETE FROM gfg_showcase_campaign WHERE id=$1 AND state='draft'
`

func (q *Queries) DeleteShowcaseDraft(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShowcaseDraft, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShowcaseCampaign = `-- name: GetShowcaseCampaign :one
SELECT id, internal_name, content_type, sponsored, linked_game_id, state, starts_at, ends_at, weight, pin_position, desktop_object_key, mobile_object_key, focal_x, focal_y, primary_action_type, primary_target, secondary_action_type, secondary_target, created_at, updated_at FROM gfg_showcase_campaign WHERE id=$1
`

func (q *Queries) GetShowcaseCampaign(ctx context.Context, id int64) (GfgShowcaseCampaign, error) {
	row := q.db.QueryRow(ctx, getShowcaseCampaign, id)
	var i GfgShowcaseCampaign
	err := row.Scan(
		&i.ID,
		&i.InternalName,
		&i.ContentType,
		&i.Sponsored,
		&i.LinkedGameID,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.Weight,
		&i.PinPosition,
		&i.DesktopObjectKey,
		&i.MobileObjectKey,
		&i.FocalX,
		&i.FocalY,
		&i.PrimaryActionType,
		&i.PrimaryTarget,
		&i.SecondaryActionType,
		&i.SecondaryTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShowcaseCampaignStats = `-- name: ListShowcaseCampaignStats :many
SELECT stat_date, subject_key, subject_kind, campaign_id, game_id, reason, valid_impressions, qualified_clicks, click_artwork, click_title, click_primary, click_secondary, impression_position_1, impression_position_2, impression_position_3, impression_position_4, session_estimate, updated_at FROM gfg_showcase_daily_stat WHERE campaign_id=$1
 AND stat_date BETWEEN $2::date AND $3::date ORDER BY stat_date
`

type ListShowcaseCampaignStatsParams struct {
	CampaignID *int64      `json:"campaign_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
}

func (q *Queries) ListShowcaseCampaignStats(ctx context.Context, arg ListShowcaseCampaignStatsParams) ([]GfgShowcaseDailyStat, error) {
	rows, err := q.db.Query(ctx, listShowcaseCampaignStats, arg.CampaignID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgShowcaseDailyStat{}
	for rows.Next() {
		var i GfgShowcaseDailyStat
		if err := rows.Scan(
			&i.StatDate,
			&i.SubjectKey,
			&i.SubjectKind,
			&i.CampaignID,
			&i.GameID,
			&i.Reason,
			&i.ValidImpressions,
			&i.QualifiedClicks,
			&i.ClickArtwork,
			&i.ClickTitle,
			&i.ClickPrimary,
			&i.ClickSecondary,
			&i.ImpressionPosition1,
			&i.ImpressionPosition2,
			&i.ImpressionPosition3,
			&i.ImpressionPosition4,
			&i.SessionEstimate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowcaseCampaigns = `-- name: ListShowcaseCampaigns :many
SELECT c.id, c.internal_name, c.content_type, c.sponsored, c.linked_game_id, c.state, c.starts_at, c.ends_at, c.weight, c.pin_position, c.desktop_object_key, c.mobile_object_key, c.focal_x, c.focal_y, c.primary_action_type, c.primary_target, c.secondary_action_type, c.secondary_target, c.created_at, c.updated_at,count(*) OVER()::bigint AS total FROM gfg_showcase_campaign c
WHERE ($1::text='' OR c.state=$1)
 AND ($2::boolean IS NULL OR c.sponsored=$2)
 AND ($3::text='' OR c.internal_name ILIKE '%'||$3||'%' OR c.id::text=$3)
 AND ($4::text='' OR CASE WHEN c.state<>'published' THEN c.state
      WHEN $5::timestamptz<c.starts_at THEN 'scheduled'
      WHEN $5::timestamptz>=c.ends_at THEN 'ended' ELSE 'active' END=$4)
ORDER BY c.id DESC LIMIT $7::integer OFFSET $6::integer
`

type ListShowcaseCampaignsParams struct {
	State         string             `json:"state"`
	Sponsored     *bool              `json:"sponsored"`
	Keyword       string             `json:"keyword"`
	DerivedStatus string             `json:"derived_status"`
	AtTime        pgtype.Timestamptz `json:"at_time"`
	RowOffset     int32              `json:"row_offset"`
	RowLimit      int32              `json:"row_limit"`
}

type ListShowcaseCampaignsRow struct {
	ID                  int64              `json:"id"`
	InternalName        string             `json:"internal_name"`
	ContentType         string             `json:"content_type"`
	Sponsored           bool               `json:"sponsored"`
	LinkedGameID        *int64             `json:"linked_game_id"`
	State               string             `json:"state"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	Weight              int32              `json:"weight"`
	PinPosition         *int16             `json:"pin_position"`
	DesktopObjectKey    *string            `json:"desktop_object_key"`
	MobileObjectKey     *string            `json:"mobile_object_key"`
	FocalX              float64            `json:"focal_x"`
	FocalY              float64            `json:"focal_y"`
	PrimaryActionType   *string            `json:"primary_action_type"`
	PrimaryTarget       *string            `json:"primary_target"`
	SecondaryActionType *string            `json:"secondary_action_type"`
	SecondaryTarget     *string            `json:"secondary_target"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Total               int64              `json:"total"`
}

func (q *Queries) ListShowcaseCampaigns(ctx context.Context, arg ListShowcaseCampaignsParams) ([]ListShowcaseCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listShowcaseCampaigns,
		arg.State,
		arg.Sponsored,
		arg.Keyword,
		arg.DerivedStatus,
		arg.AtTime,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShowcaseCampaignsRow{}
	for rows.Next() {
		var i ListShowcaseCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.InternalName,
			&i.ContentType,
			&i.Sponsored,
			&i.LinkedGameID,
			&i.State,
			&i.StartsAt,
			&i.EndsAt,
			&i.Weight,
			&i.PinPosition,
			&i.DesktopObjectKey,
			&i.MobileObjectKey,
			&i.FocalX,
			&i.FocalY,
			&i.PrimaryActionType,
			&i.PrimaryTarget,
			&i.SecondaryActionType,
			&i.SecondaryTarget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowcaseLocales = `-- name: ListShowcaseLocales :many
SELECT campaign_id, lang, enabled, title, summary, tags, editorial_note, created_at, updated_at FROM gfg_showcase_campaign_locale WHERE campaign_id=$1 ORDER BY lang
`

func (q *Queries) ListShowcaseLocales(ctx context.Context, campaignID int64) ([]GfgShowcaseCampaignLocale, error) {
	rows, err := q.db.Query(ctx, listShowcaseLocales, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgShowcaseCampaignLocale{}
	for rows.Next() {
		var i GfgShowcaseCampaignLocale
		if err := rows.Scan(
			&i.CampaignID,
			&i.Lang,
			&i.Enabled,
			&i.Title,
			&i.Summary,
			&i.Tags,
			&i.EditorialNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShowcaseQuality = `-- name: ListShowcaseQuality :many
SELECT stat_date, invalid_token_events, invalid_origin_events, filtered_user_agent_events, duplicate_impressions, duplicate_clicks, session_rate_limited, ip_rate_limited, malformed_events, updated_at FROM gfg_showcase_analytics_daily_quality
WHERE stat_date BETWEEN $1::date AND $2::date ORDER BY stat_date
`

type ListShowcaseQualityParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListShowcaseQuality(ctx context.Context, arg ListShowcaseQualityParams) ([]GfgShowcaseAnalyticsDailyQuality, error) {
	rows, err := q.db.Query(ctx, listShowcaseQuality, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GfgShowcaseAnalyticsDailyQuality{}
	for rows.Next() {
		var i GfgShowcaseAnalyticsDailyQuality
		if err := rows.Scan(
			&i.StatDate,
			&i.InvalidTokenEvents,
			&i.InvalidOriginEvents,
			&i.FilteredUserAgentEvents,
			&i.DuplicateImpressions,
			&i.DuplicateClicks,
			&i.SessionRateLimited,
			&i.IpRateLimited,
			&i.MalformedEvents,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockShowcaseCampaign = `-- name: LockShowcaseCampaign :one
SELECT id, internal_name, content_type, sponsored, linked_game_id, state, starts_at, ends_at, weight, pin_position, desktop_object_key, mobile_object_key, focal_x, focal_y, primary_action_type, primary_target, secondary_action_type, secondary_target, created_at, updated_at FROM gfg_showcase_campaign WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockShowcaseCampaign(ctx context.Context, id int64) (GfgShowcaseCampaign, error) {
	row := q.db.QueryRow(ctx, lockShowcaseCampaign, id)
	var i GfgShowcaseCampaign
	err := row.Scan(
		&i.ID,
		&i.InternalName,
		&i.ContentType,
		&i.Sponsored,
		&i.LinkedGameID,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.Weight,
		&i.PinPosition,
		&i.DesktopObjectKey,
		&i.MobileObjectKey,
		&i.FocalX,
		&i.FocalY,
		&i.PrimaryActionType,
		&i.PrimaryTarget,
		&i.SecondaryActionType,
		&i.SecondaryTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockShowcaseDomain = `-- name: LockShowcaseDomain :exec
SELECT pg_advisory_xact_lock(hashtext('gfg.showcase')::bigint)
`

func (q *Queries) LockShowcaseDomain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockShowcaseDomain)
	return err
}

const saveShowcaseCampaign = `-- name: SaveShowcaseCampaign :one
UPDATE gfg_showcase_campaign SET internal_name=$1, content_type=$2,
 sponsored=$3,linked_game_id=$4,state=$5,
 starts_at=$6,ends_at=$7,weight=$8,pin_position=$9,
 desktop_object_key=$10,mobile_object_key=$11,
 focal_x=$12,focal_y=$13,primary_action_type=$14,
 primary_target=$15,secondary_action_type=$16,
 secondary_target=$17,updated_at=now()
WHERE id=$18 RETURNING id, internal_name, content_type, sponsored, linked_game_id, state, starts_at, ends_at, weight, pin_position, desktop_object_key, mobile_object_key, focal_x, focal_y, primary_action_type, primary_target, secondary_action_type, secondary_target, created_at, updated_at
`

type SaveShowcaseCampaignParams struct {
	InternalName        string             `json:"internal_name"`
	ContentType         string             `json:"content_type"`
	Sponsored           bool               `json:"sponsored"`
	LinkedGameID        *int64             `json:"linked_game_id"`
	State               string             `json:"state"`
	StartsAt            pgtype.Timestamptz `json:"starts_at"`
	EndsAt              pgtype.Timestamptz `json:"ends_at"`
	Weight              int32              `json:"weight"`
	PinPosition         *int16             `json:"pin_position"`
	DesktopObjectKey    *string            `json:"desktop_object_key"`
	MobileObjectKey     *string            `json:"mobile_object_key"`
	FocalX              float64            `json:"focal_x"`
	FocalY              float64            `json:"focal_y"`
	PrimaryActionType   *string            `json:"primary_action_type"`
	PrimaryTarget       *string            `json:"primary_target"`
	SecondaryActionType *string            `json:"secondary_action_type"`
	SecondaryTarget     *string            `json:"secondary_target"`
	ID                  int64              `json:"id"`
}

func (q *Queries) SaveShowcaseCampaign(ctx context.Context, arg SaveShowcaseCampaignParams) (GfgShowcaseCampaign, error) {
	row := q.db.QueryRow(ctx, saveShowcaseCampaign,
		arg.InternalName,
		arg.ContentType,
		arg.Sponsored,
		arg.LinkedGameID,
		arg.State,
		arg.StartsAt,
		arg.EndsAt,
		arg.Weight,
		arg.PinPosition,
		arg.DesktopObjectKey,
		arg.MobileObjectKey,
		arg.FocalX,
		arg.FocalY,
		arg.PrimaryActionType,
		arg.PrimaryTarget,
		arg.SecondaryActionType,
		arg.SecondaryTarget,
		arg.ID,
	)
	var i GfgShowcaseCampaign
	err := row.Scan(
		&i.ID,
		&i.InternalName,
		&i.ContentType,
		&i.Sponsored,
		&i.LinkedGameID,
		&i.State,
		&i.StartsAt,
		&i.EndsAt,
		&i.Weight,
		&i.PinPosition,
		&i.DesktopObjectKey,
		&i.MobileObjectKey,
		&i.FocalX,
		&i.FocalY,
		&i.PrimaryActionType,
		&i.PrimaryTarget,
		&i.SecondaryActionType,
		&i.SecondaryTarget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveShowcaseLocale = `-- name: SaveShowcaseLocale :exec
INSERT INTO gfg_showcase_campaign_locale(campaign_id,lang,enabled,title,summary,tags,editorial_note)
VALUES($1,$2,$3,$4,$5,$6::text[],$7)
ON CONFLICT(campaign_id,lang) DO UPDATE SET enabled=EXCLUDED.enabled,title=EXCLUDED.title,
 summary=EXCLUDED.summary,tags=EXCLUDED.tags,editorial_note=EXCLUDED.editorial_note,updated_at=now()
`

type SaveShowcaseLocaleParams struct {
	CampaignID    int64    `json:"campaign_id"`
	Lang          string   `json:"lang"`
	Enabled       bool     `json:"enabled"`
	Title         string   `json:"title"`
	Summary       string   `json:"summary"`
	Tags          []string `json:"tags"`
	EditorialNote *string  `json:"editorial_note"`
}

func (q *Queries) SaveShowcaseLocale(ctx context.Context, arg SaveShowcaseLocaleParams) error {
	_, err := q.db.Exec(ctx, saveShowcaseLocale,
		arg.CampaignID,
		arg.Lang,
		arg.Enabled,
		arg.Title,
		arg.Summary,
		arg.Tags,
		arg.EditorialNote,
	)
	return err
}

const setShowcaseEligibility = `-- name: SetShowcaseEligibility :exec
UPDATE gfg_game SET showcase_eligible=$1 WHERE id=$2
`

type SetShowcaseEligibilityParams struct {
	ShowcaseEligible bool  `json:"showcase_eligible"`
	ID               int64 `json:"id"`
}

func (q *Queries) SetShowcaseEligibility(ctx context.Context, arg SetShowcaseEligibilityParams) error {
	_, err := q.db.Exec(ctx, setShowcaseEligibility, arg.ShowcaseEligible, arg.ID)
	return err
}

const showcaseGameStatus = `-- name: ShowcaseGameStatus :one
SELECT g.id,g.showcase_eligible,NOT EXISTS(SELECT 1 FROM gfg_game_tag m JOIN gfg_tag t ON t.id=m.tag_id
 WHERE m.game_id=g.id AND t.code='adult') AS sfw FROM gfg_game g WHERE g.id=$1
`

type ShowcaseGameStatusRow struct {
	ID               int64 `json:"id"`
	ShowcaseEligible bool  `json:"showcase_eligible"`
	Sfw              bool  `json:"sfw"`
}

func (q *Queries) ShowcaseGameStatus(ctx context.Context, id int64) (ShowcaseGameStatusRow, error) {
	row := q.db.QueryRow(ctx, showcaseGameStatus, id)
	var i ShowcaseGameStatusRow
	err := row.Scan(&i.ID, &i.ShowcaseEligible, &i.Sfw)
	return i, err
}

const showcasePinConflict = `-- name: ShowcasePinConflict :one
SELECT EXISTS(SELECT 1 FROM gfg_showcase_campaign c
 JOIN gfg_showcase_campaign_locale l ON l.campaign_id=c.id AND l.enabled
 WHERE c.id<>$1 AND c.state='published' AND c.pin_position IS NOT NULL
 AND c.starts_at<$2::timestamptz AND c.ends_at>$3::timestamptz
 AND l.lang=ANY($4::text[])
 AND (c.pin_position=$5::smallint OR (c.sponsored AND $6::boolean)
      OR c.linked_game_id=$7::bigint))::boolean
`

type ShowcasePinConflictParams struct {
	ID           int64              `json:"id"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	Langs        []string           `json:"langs"`
	PinPosition  int16              `json:"pin_position"`
	Sponsored    bool               `json:"sponsored"`
	LinkedGameID *int64             `json:"linked_game_id"`
}

func (q *Queries) ShowcasePinConflict(ctx context.Context, arg ShowcasePinConflictParams) (bool, error) {
	row := q.db.QueryRow(ctx, showcasePinConflict,
		arg.ID,
		arg.EndsAt,
		arg.StartsAt,
		arg.Langs,
		arg.PinPosition,
		arg.Sponsored,
		arg.LinkedGameID,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
